server:
    port: 8686

spring:
    profiles:
        active: test
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes: localhost:9200
        mongodb:
            host: localhost
            port: 27017
            database: nfse
    thymeleaf:
        mode: XHTML
        cache: true
    datasource:
        url: jdbc:oracle:thin:@//192.168.1.105:1521/wpub1
        username: atualizacaosemanal
        password: senha10
        driver-class-name: oracle.jdbc.driver.OracleDriver

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: nfse

http:
    cache:
        timeToLiveInDays: 31

logging:
    level:
        ROOT: INFO
        br:
            com:
                webpublico: INFO
        io:
            github:
                jhipster: INFO