package br.com.webpublico.domain.dto.exception;

public enum TipoValidacao {
    A005("Endereço do tomador do serviço difere do constante na base de dados do município.", "A NFS-e foi emitida considerando o endereço do tomador do serviço informado no RPS."),
    A007("A inscrição municipal do tomador do serviço está paralisada ou cancelada ou desativada ou baixada.", "A inscrição municipal do tomador do serviço informada no RPS está paralisada ou cancelada ou desativada ou baixada no cadastro municipal. A NFS-e foi emitida considerando que o tomador do serviço não está inscrito na Prefeitura."),
    E002("Data de competência superior a de emissão do RPS.", "Informe uma data de competência inferior ou igual àde emissão do RPS."),
    E008("Opção pelo simples nacional não informado.", "Se o prestador do serviço for optante pelo SIMPLES Nacional, informe '1' (sim). Caso contrário, informe '2' (não)."),
    E010("RPS já informado.", "Para essa Inscrição Municipal/CNPJ já existe um RPS informado com o mesmo número, série e tipo."),
    E011("Número do RPS não informado.", "Informe o número do RPS."),
    E014("Data da emissão do RPS não informada.", "Informe a Data da emissão do RPS conforme indicado na documentação da NFS-e.."),
    E016("A data da emissão do RPS não poderá ser superior àdata de hoje.", "Informe uma data de emissão de RPS válida."),
    E017("A data da emissão do RPS não poderá ser inferior à data de habilitação do prestador do serviço para emissão da NFS-e.", "A geração de NFS-e só é permitida para competência posterior à data de habilitação da empresa."),
    E018("O valor dos serviços deverá ser superior a R$ 0,00 (zero).", "Não é permitido envio de valor de serviços igual àzero."),
    E019("O valor das deduções deverá ser inferior ou igual ao valor dos serviços.", "Não é permitido valor de dedução superior ao valor de serviços."),
    E020("O valor das deduções deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de dedução inferior àzero (negativo)."),
    E021("O valor dos descontos deverá ser inferior ou igual ao valor dos serviços.", "Não é permitido valor de desconto superior ao valor de serviços."),
    E022("O valor dos descontos deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de desconto inferior àzero (negativo)."),
    E023("O valor do PIS deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior àzero (negativo)."),
    E024("O valor da COFINS deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior àzero (negativo)."),
    E025("O valor do INSS deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior àzero (negativo)."),
    E026("O valor do IR deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior àzero (negativo)."),
    E027("O valor da CSLL deverá ser superior ou igual a R$ 0,00 (zero).", "Não é permitido valor de retenção inferior àzero (negativo)."),
    E028("Item da lista de serviço incompatível com opção SIMPLES Nacional. ", "Consulte a legislação vigente para saber se o item da lista de serviço informado permite a opção pelo simples nacional."),
    E029("O código de serviço prestado não permite retenção de ISSQN.", "O tipo do serviço prestado não permite a retenção do ISS devido. Altere o indicador de retenção do ISSQN devido para 2 -sem retenção."),
    E030("Item da lista de serviço inexistente.", "Consulte a legislação vigente para saber o item da lista de serviço que deverá ser informado."),
    E032("Código CNAE incompatível com opção SIMPLES Nacional.", "Consulte a legislação vigente para saber se o código informado permite a opção pelo simples nacional."),
    E033("Código CNAE inexistente.", "Consulte a legislação vigente para saber o código CNAE que deverá ser informado."),
    E039("Apenas empresas inscritas neste município podem efetuar retenção de ISSQN.", "O tomador do serviço não foi encontrado na base de dados do município, não sendo permitida a retenção. Acerte o CNPJ e/ou Inscrição Municipal ou altere o campo ISSQN Retido para 2 (Sem retenção de ISSQN)."),
    E042("Código do município da prestação do serviço inválido.", "Informe o código do município onde foi prestado o serviço, conforme Tabela de Municípios do IBGE."),
    E047("CPF/CNPJ do tomador do serviço incorreto.", "Informe corretamente o CPF/CNPJ do tomador do serviço."),
    E052("O tomador do serviço informado é o próprio prestador do serviço.", "Na emissão da NFS-e não é permitido que o prestador do serviço seja igual ao tomador do serviço."),
    E053("O campo Inscrição Municipal do tomador do serviço só deverá ser preenchido para tomadores estabelecidos neste município.", "Para tomador de serviço estabelecido fora deste município não deve ser preenchido o campo Inscrição municipal."),
    E065("Inscrição Municipal do intermediário do serviço não esta vinculada ao CNPJ/CPF informado.", "A inscrição municipal informada não está vinculada ao intermediário do serviço identificado pelo CNPJ ou CPF."),
    E069("Quantidade de RPS incorreta.", "A quantidade de RPS informada difere da quantidade de RPS do lote."),
    E077("Número da NFS-e não informado", "Informe o número da NFS-e."),
    E078("Número da NFS-e inexistente na base de dados para o prestador do serviço pesquisado.", "Informe corretamente o número da NFS-e."),
    E079("NFS-e já está cancelada.", "Verifique e informe corretamente os dados da NFS-e que deseja cancelar."),
    E087("Número de lote inexistente na base de dados.", "Confira se o lote foi enviado e informe o número correto."),
    E089("Não existe na base de dados uma NFS-e emitida para o número de RPS informado.", "Informe corretamente o número do RPS."),
    E091("Esse RPS não consta em nossa base de dados.", "Solicite do prestador do serviço a emissão da NFS-e."),
    E092("RPS ainda não convertido em NFS-e.", "Efetue nova consulta mais tarde."),
    E099("Valor da retenção deverá ser inferior ou igual ao valor dos serviços.", "Não é permitido valor de retenção superior ao valor de serviços. E133Data final posterior a data de hoje.Informe uma data final igual ou anterior a data de hoje."),
    E134("Data final anterior à data inicial.", "Informe uma data final igual ou superior a data inicial da pesquisa."),
    E138("Usuário não autorizado a realizaro serviço.", "Informe os dados de um usuário autorizado a executar o serviço."),
    E167("Município informado não pertence à Unidade Federativa.", "Acerte o município ou a Unidade Federativa."),
    E168("CEP do tomador do serviço informado indevidamente.", "Não informe o CEP do tomador do serviço quando ele for domiciliado no exterior ou não for identificado."),
    E169("CNPJ/CPF do tomador do serviço informado indevidamente.", "Não informe o CNPJ/CPF do tomador do serviço quando ele for domiciliado no exterior ou não for identificado."),
    E175("O somatório das deduções e do desconto incondicionado está maior que o valor dos serviços.", "O preço do serviço deve ser maior ou igual à soma das deduções com o desconto incondicionado."),
    E176("O somatório dos descontos, retenções federais e ISSQN retido na fonte estãomaioresque o valor dos serviços.", "O preço do serviço deve ser maior ou igual à soma dos tributos federais, o ISSQN devido e os descontos."),
    E177("Pessoa Física não pode efetuar a retenção do ISSQNTomador de serviço pessoa física não pode reter o ISSQN.", "Altere o indicador de retenção do ISSQN para 2 -sem retenção."),
    E178("Lote aguardando processamento.", "O lote de RPS correspondente ao protocolo informado foi recebido pela Prefeitura, mas ainda não foi processado."),
    E179("Erro na autenticação.", "O usuário correspondente ao documento utilizado para autenticação não possui autorização para realizar o serviço para a empresa parametrizada via CNPJ e inscrição municipal do arquivo."),
    E191("Tipo do RPS inválido.", "Neste município utilizar somente o Tipo 1 -RPSE206Cancelamento da NFS-e por erro na emissão não pode ser feito por esse serviço.Utilize o serviço de substituição de NFS-e."),
    E208("Cancelamento de NFS-e com tomador do serviço não informado não pode ser feito por esse serviço.", "O cancelamento de uma NFS-e com tomador do serviço não informado deverá ser feito por meio de processo administrativo aberto na repartição fazendária."),
    E213("Código de cancelamento informado de uso exclusivo da Prefeitura.", "Código de motivo de cancelamento <3-Erro de assinatura> e <5-Erro de processamento> é de uso exclusivo da Prefeitura."),
    E216("Não é permitida a substituição de RPS.", "O campo RpsSubstituido não pode ser preenchido para este município."),
    E220("Valor do ISSQN informado indevidamente.", "O valor do ISSQN será calculado pela Prefeitura e não deve ser informado pelo contribuinte."),
    E221("Alíquota informada indevidamente.", "A alíquota do ISSQN só deve ser informada quando: o ISSQN for devido a outro município ou o prestador do serviço for optante pelo Simples Nacional e houver retenção do ISSQN. Em outras situações a alíquota a ser aplicada será determinada pela Prefeitura."),
    E227("Alíquota Serviços fora do intervalo de 2% e 5%", "Quando o local da incidência for diferente deste município esse campo deve ser maior ou igual a 2% e menor ou igual a 5%."),
    E228("Para esta prestação de serviços a alíquota do ISSQN é obrigatória.", "Informe um valor percentual da alíquota de ISSQN, que deve ser maior ou igual a 2% e menor ou igual a 5%."),
    E229("A Inscrição Municipal do tomador do serviço não existe na base de dadosda Prefeitura.", "Informe corretamente a Inscrição Municipal do tomador do serviço"),
    E233("Lote já processado.", " Atribua um novo número ao lote de RPS, caso os RPS nele contidos ainda não tenham sidos processados."),
    E241("Retenções de Tributos Federais só podem ser efetuadaspor tomador deserviçospessoa jurídica.", "Preencher os campos de retenções federais com zeros."),
    E243("Esta NFS-e não deverá ter o ISSQN Retido pelo tomador do serviço.", " Consulte a legislação vigente para saber as regras de retenção do ISSQN na fonte e selecione ISS Retido = 2 (NÃO)."),
    E249("Código do município de incidência do ISSQN incorreto.", "Contribuintes com regime especial de tributação 'Microempresário Individual' (MEI) não pode emitir NFS-e com município de incidência diferente do município gerador."),
    E251("Para o regime especial <Estimativa> não é permitida a emissão de NFS-e.", "Consulte a legislação aplicável e verifique as situações de emissão de NFS-e."),
    E252("Para o regime especial <Cooperativa> não é permitida a emissão de NFS-e.", "Consulte a legislação aplicável e verifique as situações de emissão de NFS-e."),
    E253("A data da nova competência não deve ser inferior à competência de criação da NFS-e.", "Altere a data da competência."),
    E255("O status atual desta nota não permite alteração.", "A NFS-e não pode ser alterada."),
    E262("Inscrição municipal paralisada, cancelada ou desativada.", "Prestador do serviço com inscrição municipal paralisada, cancelada ou desativada não pode utilizar NFS-e."),
    E273("PIS retido incorreto.Apenas pessoas jurídicas podem reter tributos.", "Se o tomador do serviço é pessoa física, o valor do tributo retido deve ser igual a zero."),
    E274("COFINS retida incorreta.Apenas pessoas jurídicas podem reter tributos.", "Se o tomador do serviço é pessoa física, o valor do tributo retido deve ser igual a zero."),
    E275("Contribuição ao INSS retida incorreta.Apenas pessoas jurídicas podem reter tributos.", "Se o tomador do serviço é pessoa física, o valor do tributo retido deve ser igual a zero."),
    E276("Imposto de renda retido incorreto.Apenas pessoas jurídicas podem reter tributos.", "Se o tomador do serviço é pessoa física, o valor do tributo retido deve ser igual a zero."),
    E277("CSLL retida incorreta.Apenas pessoas jurídicas podem reter tributos.", "Se o tomador do serviço é pessoa física, o valor do tributo retido deve ser igual a zero."),
    E278("Indicador de ISSQN retido incorreto.Empresa com inscrição municipal paralisada, cancelada ou desativada não pode reter ISSQN.", "Altere o indicador de retenção do ISSQN para 2 -sem retenção."),
    E282("Responsável/Retentor informado indevido.", "O campo Responsável/Retentor somente deverá ser preenchido quando o ISSQN for retido na fonte.E285País da prestação do serviço não informado.Quando a exigibilidade do ISSQN for <Exportação> informar o país da prestação do serviço."),
    E287("País da prestação do serviço indevido.", "O código do país da prestação do serviço somente deverá ser informado quando a exigibilidade do ISSQN for <Exportação>."),
    E290("País do tomador do serviço não informado.", "Quando a exigibilidade do ISSQN for <Exportação> informar o país do tomador do serviço."),
    E292("País do tomador do serviço indevido.", "O código do país do tomador do serviço somente deverá ser informado quando o município for igual a <9999999>."),
    E293("Intermediário do serviço não informado.", "Quando o campo Responsável/Retenção for igual a <2> a qualificação do intermediário do serviço é informação obrigatória."),
    E294("CPF do intermediário do serviço informado indevidamente.", "O intermediário do serviço deve ser pessoa jurídica."),
    E296("CNPJ/CPF do intermediário do serviço não informado.", "Informe o CNPJ/CPF do intermediário do serviço."),
    E297("CNPJ/CPF do intermediário do serviço não consta da base de dados.", "O intermediário do serviço não foi encontrado na base de dados do município,"),
    E298("CNPJ/CPF do intermediário do serviço incorreto.", "Informe corretamente o CNPJ/CPF do intermediário do serviço."),
    E299("Inscrição municipal do intermediário do serviço não informada.", "Quando o CPF/CNPJ do intermediário do serviço estiver vinculado a mais de uma inscrição municipal esta informação é obrigatória."),
    E300("Inscrição municipal do intermediário do serviço não consta da base de dadosO intermediário do serviço não foi encontrado na base de dados do município,E302.", "Código da obra não informado.Para o serviço informado o código da obra é informação obrigatória."),
    E303("Código da obra informada indevidamente.", "O serviço informado não permite a informação do código da obra."),
    E304("ART informada indevidamente.", "O serviço informado não permite indicação de ART."),
    E305("ART não informada.", "Para o serviço informado a ART -Anotação de Responsabilidade Técnica -é informação obrigatória."),
    E311("Código do município de incidência do ISSQN não informadoA informação do código do município da incidência do 9", "ISSQN é obrigatóriaquando <Exigibilidade do ISS> for tipo <1 -Exigível>, <6 -Exigibilidade Suspensa por Decisão Judicial> ou <7 -Exigibilidade Suspensa por Processo Administrativo>. Consulte a Tabela de Municípios do IBGE para preenchimento do campo."),
    E313("Número do processo informado indevidamente.", "Somente deverá ser informado o número do processo quando <Exigibilidade do ISS> for tipo <6 -Exigibilidade Suspensa por Decisão Judicial> ou <7 -Exigibilidade Suspensa por Processo Administrativo>."),
    E314("Número do processo não informado.", "A informação do número do processo é obrigatória quando <Exigibilidade do ISS> for tipo <6 -Exigibilidade Suspensa por Decisão Judicial> ou <7 -Exigibilidade Suspensa por Processo Administrativo>."),
    E327("O regime de tributação informado difere do registrado na Prefeitura.", "Procure a Prefeitura para atualizar o regime de tributação no cadastro do contribuinte."),
    E329("Apenas serviços tributados podem sofrer retenção de ISSQN.", "A retenção na fonte é permitida somente se o campo <Exigibilidade do ISS> for igual a <1 -Exigível>."),
    E330("Contribuintes enquadrados como MEI do simples nacional não podem sofrer retenção de ISSQN.", "Empresas enquadradas como MEI do simples nacional não devem sofrer retenção na fonte do ISSQN."),
    E331("Contribuintes enquadrados como Microempresa Municipal não podem sofrer retenção de ISSQN.", "Empresas enquadradas como Microempresa Municipal não devem sofrer retenção na fonte do ISSQN."),
    E332("Contribuintes enquadrados como Estimativa não podem sofrer retenção de ISSQN.", "Empresas enquadradas como Estimativa não devem sofrer retenção na fonte do ISSQN."),
    E333("Contribuintes enquadrados como Sociedade de Profissionais não podem sofrer retenção de ISSQN.", "Empresas enquadradas como Sociedade de Profissionais não devem sofrer retenção na fonte do ISSQN."),
    E334("Contribuintes enquadrados como Incentivador Fiscal não podem sofrer retenção de ISSQN.", "Empresas enquadradas como Incentivador Fiscal não devem sofrer retenção na fonte do ISSQN."),
    E335("Empresas cadastradas com CPF não podem sofrer retenção de ISSQN.", "Empresas cadastradas com CPF não devem sofrer retenção na fonte do ISSQN."),
    E336("Inscrição municipal do tomador do serviço indevida.", "Não informe o campo inscrição municipal do tomador do serviço quando este for do exterior"),
    E341("Alíquota do ISSQN não informado.", "Quando o ISSQN é devido a outro município, alíquota deve ser informada pelo prestador do serviço."),
    E342("Informação de Incentivador Fiscal não confere com o cadastro da prefeitura.", "Acerte o campo Incentivador Fiscal"),
    E344("Item da lista de serviço informado para a operação não permite tributação fora do município.", "Consulte a legislação vigente para saber se o item informado permite a tributação fora do município."),
    S001("Nenhum resultado encontrado.", "Alterar o filtro."),
    S002("Requerente inválido.", "Confira os dados do prestador, a senha possa ser obtida no portal web, configurações da empresa e campo CHAVE WS"),
    S003("Somente serviço de homologação.", "Para este requerente somente o ambiente de homologação está habilitado, ative o flag de homologação."),
    S004("Código do Município %1$d informado para %2$s não existe na Tabela de Municípios do IBGE.", "Informe um novo código existente.Informe o código do município conforme Tabela de Municípios do IBGE."),
    S005("Exigibilidade não encontrada.", "Informe um código de exigibilidade válido."),
    S006("Regime fiscal não encontrado.", "Informe um código de regime fiscal válido."),
    S007("Nota fiscal com itens de alíquotasdiferentes.", "Informe apenas itens com a mesma alíquota."),
    S008("Valor deduções não deve ser superior ao valor dos serviços.", "Corrija o valor das deduções ou dos serviços"),
    S009("Valor deduções não deve ser superior a %1$.2f%% do valor dos serviços.", "Corrija o valor das deduções ou dos serviços"),
    S010("Valor deduçõesnão confere com a soma do valor líquido dos itens de dedução.", "Corrija o valor das deduções ou itens de dedução"),
    S011("Valor NFSE deve ser superior a R$ 0,00 (zero).", "Por favor,verifique os valores da NFSe, a soma dos valores líquidosdos itens, menos os descontos e as deduções estãogerando um valor negativo."),
    S012("O valor liquido do item \"%s\" não corresponde com o calculo de quantidade * valor unitário -desconto.", "Corrija o valor liquido do item ou um de seus componentes."),
    S013("O valor do desconto incondicionado não confere com a soma dos descontos lançados nos itens.", "Corrija o valor do desconto incondicionado ou os valores de desconto nos itens."),
    S014("Código CNAE incompatível com opção Micro Empreendedor Individual.", "Consulte a legislação vigente para saber se o código informado permite a opção pelo micro empreendedor individual."),
    S015("Código lista serviços incompatível com opção Micro Empreendedor  Individual.", "Consulte a legislação vigente para saber se o códigoinformado permite a opção pelo micro empreendedorindividual."),
    S016("País não encontrado.", "Informe o código do país conforme Tabela de Países do BACEN."),
    S017("Requerente não credenciado.", "Informe um requerente credenciado."),
    S018("Inscrição Municipal Incorreta.", "Inscrição Municipal do prestador está diferente da Inscrição do Requerente os dois devem ser iguais."),
    S019("O serviço %1$s é divergente do outros itens.", "Item da Lista de Serviço divergente em algum dos itens do RPS.S020O CNAE %1$s é divergente do outros itens.O CNAE está divergente em algum dos itens do RPS."),
    S020("CNAE Informado Incompatível.", "O CNAE está divergente em algum dos itens do RPS."),
    S021("Município de incidência não permitido.", "Altere o município de incidência para o município válido."),
    S022("Dedução não permitida.", "O item da Listade serviços não permite dedução."),
    S023("Valor total não corresponde a soma dos itens.", "Corrija o valor liquido dos itens."),
    S025("Municípiode incidêncianão permitido.", "O item da lista de serviços não permite ISSQN retido para o municípiode incidênciaindicado."),
    S027("Serviço não habilitado para utilização.", "Entre em contato com o setor de tributação."),
    S028("Enquadramento Fiscal e Tipo de ISS não Definido.", "Entre em contato com o setor de tributação."),
    S999("Erro Interno.", "Erro inesperado entre em contato com o suporte técnico"),
    W001("Valor do ISSQN superior ao valor da NFSE.", "Por favor corrija o valor do ISSQN."),
    W002("Nenhuma nota fiscal encontrada com os filtros informados.", "Por favor corrija os filtros."),
    W003("Tomador substituto tributário, retenção obrigatória.", "Serviços prestados a substitutos tributários devem reter o issqn obrigatóriamente"),
    W004("Xml invalido.", "Não foi possível converter o xml"),
    W005("Nenhum item de serviço informado.", "Por favor adicione ao menos um item de serviço"),
    W006("Nota fiscal substituidora não informada.", "Por favor informe os dados da nota fiscal substituidora."),
    W007("Nota fiscal substituida não informada.", "Por favor informe os dados da nota fiscal substituida."),
    W008("Serviço movido para outro endereço.", "Por favor informe o endereço correto.");

    private String descricao;
    private String sugestao;

    TipoValidacao(String descricao, String sugestao) {
        this.descricao = descricao;
        this.sugestao = sugestao;
    }

    public String getDescricao() {
        return descricao;
    }

    public String getSugestao() {
        return sugestao;
    }
}
