//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import br.com.webpublico.domain.dto.nfse203.TcIdentificacaoRequerente;
import br.com.webpublico.domain.dto.nfse203.TcLoteRps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoRequerente" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcIdentificacaoRequerente"/>
 *         &lt;element name="LoteRps" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcLoteRps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identificacaoRequerente",
    "loteRps"
})
@XmlRootElement(name = "EnviarLoteRpsSincronoEnvio")
public class EnviarLoteRpsSincronoEnvio {

    @XmlElement(name = "IdentificacaoRequerente", required = true)
    protected TcIdentificacaoRequerente identificacaoRequerente;
    @XmlElement(name = "LoteRps", required = true)
    protected TcLoteRps loteRps;

    /**
     * Gets the value of the identificacaoRequerente property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoRequerente }
     *     
     */
    public TcIdentificacaoRequerente getIdentificacaoRequerente() {
        return identificacaoRequerente;
    }

    /**
     * Sets the value of the identificacaoRequerente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoRequerente }
     *     
     */
    public void setIdentificacaoRequerente(TcIdentificacaoRequerente value) {
        this.identificacaoRequerente = value;
    }

    /**
     * Gets the value of the loteRps property.
     * 
     * @return
     *     possible object is
     *     {@link TcLoteRps }
     *     
     */
    public TcLoteRps getLoteRps() {
        return loteRps;
    }

    /**
     * Sets the value of the loteRps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcLoteRps }
     *     
     */
    public void setLoteRps(TcLoteRps value) {
        this.loteRps = value;
    }

}
