//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import br.com.webpublico.domain.dto.nfse203.TcDeclaracaoPrestacaoServico;
import br.com.webpublico.domain.dto.nfse203.TcIdentificacaoRequerente;
import br.com.webpublico.domain.dto.nfse203.TcPedidoCancelamento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoRequerente" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcIdentificacaoRequerente"/>
 *         &lt;element name="SubstituicaoNfse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Pedido" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcPedidoCancelamento"/>
 *                   &lt;element name="Rps" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcDeclaracaoPrestacaoServico"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identificacaoRequerente",
    "substituicaoNfse"
})
@XmlRootElement(name = "SubstituirNfseEnvio")
public class SubstituirNfseEnvio {

    @XmlElement(name = "IdentificacaoRequerente", required = true)
    protected TcIdentificacaoRequerente identificacaoRequerente;
    @XmlElement(name = "SubstituicaoNfse", required = true)
    protected SubstituicaoNfse substituicaoNfse;

    /**
     * Gets the value of the identificacaoRequerente property.
     *
     * @return
     *     possible object is
     *     {@link TcIdentificacaoRequerente }
     *
     */
    public TcIdentificacaoRequerente getIdentificacaoRequerente() {
        return identificacaoRequerente;
    }

    /**
     * Sets the value of the identificacaoRequerente property.
     *
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoRequerente }
     *
     */
    public void setIdentificacaoRequerente(TcIdentificacaoRequerente value) {
        this.identificacaoRequerente = value;
    }

    /**
     * Gets the value of the substituicaoNfse property.
     *
     * @return
     *     possible object is
     *     {@link SubstituicaoNfse }
     *
     */
    public SubstituicaoNfse getSubstituicaoNfse() {
        return substituicaoNfse;
    }

    /**
     * Sets the value of the substituicaoNfse property.
     *
     * @param value
     *     allowed object is
     *     {@link SubstituicaoNfse }
     *
     */
    public void setSubstituicaoNfse(SubstituicaoNfse value) {
        this.substituicaoNfse = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Pedido" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcPedidoCancelamento"/>
     *         &lt;element name="Rps" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcDeclaracaoPrestacaoServico"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pedido",
        "rps"
    })
    public static class SubstituicaoNfse {

        @XmlElement(name = "Pedido", required = true)
        protected TcPedidoCancelamento pedido;
        @XmlElement(name = "Rps", required = true)
        protected TcDeclaracaoPrestacaoServico rps;

        /**
         * Gets the value of the pedido property.
         *
         * @return
         *     possible object is
         *     {@link TcPedidoCancelamento }
         *
         */
        public TcPedidoCancelamento getPedido() {
            return pedido;
        }

        /**
         * Sets the value of the pedido property.
         *
         * @param value
         *     allowed object is
         *     {@link TcPedidoCancelamento }
         *
         */
        public void setPedido(TcPedidoCancelamento value) {
            this.pedido = value;
        }

        /**
         * Gets the value of the rps property.
         *
         * @return
         *     possible object is
         *     {@link TcDeclaracaoPrestacaoServico }
         *
         */
        public TcDeclaracaoPrestacaoServico getRps() {
            return rps;
        }

        /**
         * Sets the value of the rps property.
         *
         * @param value
         *     allowed object is
         *     {@link TcDeclaracaoPrestacaoServico }
         *     
         */
        public void setRps(TcDeclaracaoPrestacaoServico value) {
            this.rps = value;
        }

    }

}
