//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDadosDeducao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDadosDeducao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoDeducao" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsTipoDeducao"/>
 *         &lt;element name="Cpf" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsCpf" minOccurs="0"/>
 *         &lt;element name="Cnpj" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsCnpj" minOccurs="0"/>
 *         &lt;element name="NumeroNotaFiscalReferencia" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsNumeroNfse" minOccurs="0"/>
 *         &lt;element name="ValorTotalNotaFiscal" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="PercentualADeduzir" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorADeduzir" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDadosDeducao", propOrder = {
    "tipoDeducao",
    "cpf",
    "cnpj",
    "numeroNotaFiscalReferencia",
    "valorTotalNotaFiscal",
    "percentualADeduzir",
    "valorADeduzir"
})
public class TcDadosDeducao {

    @XmlElement(name = "TipoDeducao", required = true)
    protected String tipoDeducao;
    @XmlElement(name = "Cpf")
    protected String cpf;
    @XmlElement(name = "Cnpj")
    protected String cnpj;
    @XmlElement(name = "NumeroNotaFiscalReferencia")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroNotaFiscalReferencia;
    @XmlElement(name = "ValorTotalNotaFiscal")
    protected BigDecimal valorTotalNotaFiscal;
    @XmlElement(name = "PercentualADeduzir")
    protected BigDecimal percentualADeduzir;
    @XmlElement(name = "ValorADeduzir")
    protected BigDecimal valorADeduzir;

    /**
     * Gets the value of the tipoDeducao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDeducao() {
        return tipoDeducao;
    }

    /**
     * Sets the value of the tipoDeducao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDeducao(String value) {
        this.tipoDeducao = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the cnpj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnpj() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnpj(String value) {
        this.cnpj = value;
    }

    /**
     * Gets the value of the numeroNotaFiscalReferencia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumeroNotaFiscalReferencia() {
        return numeroNotaFiscalReferencia;
    }

    /**
     * Sets the value of the numeroNotaFiscalReferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroNotaFiscalReferencia(BigInteger value) {
        this.numeroNotaFiscalReferencia = value;
    }

    /**
     * Gets the value of the valorTotalNotaFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalNotaFiscal() {
        return valorTotalNotaFiscal;
    }

    /**
     * Sets the value of the valorTotalNotaFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalNotaFiscal(BigDecimal value) {
        this.valorTotalNotaFiscal = value;
    }

    /**
     * Gets the value of the percentualADeduzir property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentualADeduzir() {
        return percentualADeduzir;
    }

    /**
     * Sets the value of the percentualADeduzir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentualADeduzir(BigDecimal value) {
        this.percentualADeduzir = value;
    }

    /**
     * Gets the value of the valorADeduzir property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorADeduzir() {
        return valorADeduzir;
    }

    /**
     * Sets the value of the valorADeduzir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorADeduzir(BigDecimal value) {
        this.valorADeduzir = value;
    }

}
