//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import br.com.webpublico.domain.dto.nfse203.TcIdentificacaoRps;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tcInfRps complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcInfRps">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoRps" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcIdentificacaoRps"/>
 *         &lt;element name="DataEmissao" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsData"/>
 *         &lt;element name="Status" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsStatusRps"/>
 *         &lt;element name="RpsSubstituido" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcIdentificacaoRps" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcInfRps", propOrder = {
    "identificacaoRps",
    "dataEmissao",
    "status",
    "rpsSubstituido"
})
public class TcInfRps {

    @XmlElement(name = "IdentificacaoRps", required = true)
    protected TcIdentificacaoRps identificacaoRps;
    @XmlElement(name = "DataEmissao", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataEmissao;
    @XmlElement(name = "Status")
    protected byte status;
    @XmlElement(name = "RpsSubstituido")
    protected TcIdentificacaoRps rpsSubstituido;

    /**
     * Gets the value of the identificacaoRps property.
     *
     * @return
     *     possible object is
     *     {@link TcIdentificacaoRps }
     *
     */
    public TcIdentificacaoRps getIdentificacaoRps() {
        return identificacaoRps;
    }

    /**
     * Sets the value of the identificacaoRps property.
     *
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoRps }
     *
     */
    public void setIdentificacaoRps(TcIdentificacaoRps value) {
        this.identificacaoRps = value;
    }

    /**
     * Gets the value of the dataEmissao property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDataEmissao() {
        return dataEmissao;
    }

    /**
     * Sets the value of the dataEmissao property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDataEmissao(XMLGregorianCalendar value) {
        this.dataEmissao = value;
    }

    /**
     * Gets the value of the status property.
     *
     */
    public byte getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     */
    public void setStatus(byte value) {
        this.status = value;
    }

    /**
     * Gets the value of the rpsSubstituido property.
     *
     * @return
     *     possible object is
     *     {@link TcIdentificacaoRps }
     *
     */
    public TcIdentificacaoRps getRpsSubstituido() {
        return rpsSubstituido;
    }

    /**
     * Sets the value of the rpsSubstituido property.
     *
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoRps }
     *     
     */
    public void setRpsSubstituido(TcIdentificacaoRps value) {
        this.rpsSubstituido = value;
    }

}
