//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import br.com.webpublico.domain.dto.nfse203.TcDadosDeducao;
import br.com.webpublico.domain.dto.nfse203.TsUnidade;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for tcItemServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcItemServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemListaServico" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsItemListaServico"/>
 *         &lt;element name="CodigoCnae" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsCodigoCnae"/>
 *         &lt;element name="Descricao" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsDescricao"/>
 *         &lt;element name="Unidade" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsUnidade" minOccurs="0"/>
 *         &lt;element name="Tributavel" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao"/>
 *         &lt;element name="Quantidade" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValorQuantidade"/>
 *         &lt;element name="ValorUnitario" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValorUnitario"/>
 *         &lt;element name="ValorDesconto" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorLiquido" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor"/>
 *         &lt;element name="DadosDeducao" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tcDadosDeducao" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcItemServico", propOrder = {
    "itemListaServico",
    "codigoCnae",
    "descricao",
    "unidade",
    "tributavel",
    "quantidade",
    "valorUnitario",
    "valorDesconto",
    "valorLiquido",
    "dadosDeducao"
})
public class TcItemServico {

    @XmlElement(name = "ItemListaServico", required = true)
    protected String itemListaServico;
    @XmlElement(name = "CodigoCnae")
    protected int codigoCnae;
    @XmlElement(name = "Descricao", required = true)
    protected String descricao;
    @XmlElement(name = "Unidade")
    @XmlSchemaType(name = "string")
    protected TsUnidade unidade;
    @XmlElement(name = "Tributavel")
    protected byte tributavel;
    @XmlElement(name = "Quantidade", required = true)
    protected BigDecimal quantidade;
    @XmlElement(name = "ValorUnitario", required = true)
    protected BigDecimal valorUnitario;
    @XmlElement(name = "ValorDesconto")
    protected BigDecimal valorDesconto;
    @XmlElement(name = "ValorLiquido", required = true)
    protected BigDecimal valorLiquido;
    @XmlElement(name = "DadosDeducao")
    protected TcDadosDeducao dadosDeducao;

    /**
     * Gets the value of the itemListaServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemListaServico() {
        return itemListaServico;
    }

    /**
     * Sets the value of the itemListaServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemListaServico(String value) {
        this.itemListaServico = value;
    }

    /**
     * Gets the value of the codigoCnae property.
     * 
     */
    public int getCodigoCnae() {
        return codigoCnae;
    }

    /**
     * Sets the value of the codigoCnae property.
     * 
     */
    public void setCodigoCnae(int value) {
        this.codigoCnae = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the unidade property.
     *
     * @return possible object is
     * {@link TsUnidade }
     */
    public TsUnidade getUnidade() {
        return unidade;
    }

    /**
     * Sets the value of the unidade property.
     *
     * @param value allowed object is
     *              {@link TsUnidade }
     */
    public void setUnidade(TsUnidade value) {
        this.unidade = value;
    }

    /**
     * Gets the value of the tributavel property.
     * 
     */
    public byte getTributavel() {
        return tributavel;
    }

    /**
     * Sets the value of the tributavel property.
     * 
     */
    public void setTributavel(byte value) {
        this.tributavel = value;
    }

    /**
     * Gets the value of the quantidade property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidade() {
        return quantidade;
    }

    /**
     * Sets the value of the quantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidade(BigDecimal value) {
        this.quantidade = value;
    }

    /**
     * Gets the value of the valorUnitario property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorUnitario() {
        return valorUnitario;
    }

    /**
     * Sets the value of the valorUnitario property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorUnitario(BigDecimal value) {
        this.valorUnitario = value;
    }

    /**
     * Gets the value of the valorDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorDesconto() {
        return valorDesconto;
    }

    /**
     * Sets the value of the valorDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorDesconto(BigDecimal value) {
        this.valorDesconto = value;
    }

    /**
     * Gets the value of the valorLiquido property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorLiquido() {
        return valorLiquido;
    }

    /**
     * Sets the value of the valorLiquido property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorLiquido(BigDecimal value) {
        this.valorLiquido = value;
    }

    /**
     * Gets the value of the dadosDeducao property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosDeducao }
     *     
     */
    public TcDadosDeducao getDadosDeducao() {
        return dadosDeducao;
    }

    /**
     * Sets the value of the dadosDeducao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosDeducao }
     *     
     */
    public void setDadosDeducao(TcDadosDeducao value) {
        this.dadosDeducao = value;
    }

}
