//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for tcValoresDeclaracaoServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcValoresDeclaracaoServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValorServicos" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor"/>
 *         &lt;element name="ValorDeducoes" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="AliquotaPis" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="RetidoPis" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="ValorPis" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="AliquotaCofins" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="RetidoCofins" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="ValorCofins" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="AliquotaInss" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="RetidoInss" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="ValorInss" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="AliquotaIr" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="RetidoIr" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="ValorIr" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="AliquotaCsll" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="RetidoCsll" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="ValorCsll" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="AliquotaCpp" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="RetidoCpp" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="ValorCpp" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="OutrasRetencoes" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="RetidoOutrasRetencoes" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsSimNao" minOccurs="0"/>
 *         &lt;element name="AliquotaTotTributos" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="ValTotTributos" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="ValorIss" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="Aliquota" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsAliquota" minOccurs="0"/>
 *         &lt;element name="DescontoIncondicionado" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *         &lt;element name="DescontoCondicionado" type="{http://nfse.webpublico.com.br/iss/nfse_v2_03.xsd}tsValor" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcValoresDeclaracaoServico", propOrder = {
    "valorServicos",
    "valorDeducoes",
    "aliquotaPis",
    "retidoPis",
    "valorPis",
    "aliquotaCofins",
    "retidoCofins",
    "valorCofins",
    "aliquotaInss",
    "retidoInss",
    "valorInss",
    "aliquotaIr",
    "retidoIr",
    "valorIr",
    "aliquotaCsll",
    "retidoCsll",
    "valorCsll",
    "aliquotaCpp",
    "retidoCpp",
    "valorCpp",
    "outrasRetencoes",
    "retidoOutrasRetencoes",
    "aliquotaTotTributos",
    "valTotTributos",
    "valorIss",
    "aliquota",
    "descontoIncondicionado",
    "descontoCondicionado"
})
public class TcValoresDeclaracaoServico {

    @XmlElement(name = "ValorServicos", required = true)
    protected BigDecimal valorServicos;
    @XmlElement(name = "ValorDeducoes")
    protected BigDecimal valorDeducoes;
    @XmlElement(name = "AliquotaPis")
    protected BigDecimal aliquotaPis;
    @XmlElement(name = "RetidoPis")
    protected Byte retidoPis;
    @XmlElement(name = "ValorPis")
    protected BigDecimal valorPis;
    @XmlElement(name = "AliquotaCofins")
    protected BigDecimal aliquotaCofins;
    @XmlElement(name = "RetidoCofins")
    protected Byte retidoCofins;
    @XmlElement(name = "ValorCofins")
    protected BigDecimal valorCofins;
    @XmlElement(name = "AliquotaInss")
    protected BigDecimal aliquotaInss;
    @XmlElement(name = "RetidoInss")
    protected Byte retidoInss;
    @XmlElement(name = "ValorInss")
    protected BigDecimal valorInss;
    @XmlElement(name = "AliquotaIr")
    protected BigDecimal aliquotaIr;
    @XmlElement(name = "RetidoIr")
    protected Byte retidoIr;
    @XmlElement(name = "ValorIr")
    protected BigDecimal valorIr;
    @XmlElement(name = "AliquotaCsll")
    protected BigDecimal aliquotaCsll;
    @XmlElement(name = "RetidoCsll")
    protected Byte retidoCsll;
    @XmlElement(name = "ValorCsll")
    protected BigDecimal valorCsll;
    @XmlElement(name = "AliquotaCpp")
    protected BigDecimal aliquotaCpp;
    @XmlElement(name = "RetidoCpp")
    protected Byte retidoCpp;
    @XmlElement(name = "ValorCpp")
    protected BigDecimal valorCpp;
    @XmlElement(name = "OutrasRetencoes")
    protected BigDecimal outrasRetencoes;
    @XmlElement(name = "RetidoOutrasRetencoes")
    protected Byte retidoOutrasRetencoes;
    @XmlElement(name = "AliquotaTotTributos")
    protected BigDecimal aliquotaTotTributos;
    @XmlElement(name = "ValTotTributos")
    protected BigDecimal valTotTributos;
    @XmlElement(name = "ValorIss")
    protected BigDecimal valorIss;
    @XmlElement(name = "Aliquota")
    protected BigDecimal aliquota;
    @XmlElement(name = "DescontoIncondicionado")
    protected BigDecimal descontoIncondicionado;
    @XmlElement(name = "DescontoCondicionado")
    protected BigDecimal descontoCondicionado;

    /**
     * Gets the value of the valorServicos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorServicos() {
        return valorServicos;
    }

    /**
     * Sets the value of the valorServicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorServicos(BigDecimal value) {
        this.valorServicos = value;
    }

    /**
     * Gets the value of the valorDeducoes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorDeducoes() {
        return valorDeducoes;
    }

    /**
     * Sets the value of the valorDeducoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorDeducoes(BigDecimal value) {
        this.valorDeducoes = value;
    }

    /**
     * Gets the value of the aliquotaPis property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getAliquotaPis() {
        return aliquotaPis;
    }

    /**
     * Sets the value of the aliquotaPis property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaPis(BigDecimal value) {
        this.aliquotaPis = value;
    }

    /**
     * Gets the value of the retidoPis property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getRetidoPis() {
        return retidoPis;
    }

    /**
     * Sets the value of the retidoPis property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoPis(Byte value) {
        this.retidoPis = value;
    }

    /**
     * Gets the value of the valorPis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorPis() {
        return valorPis;
    }

    /**
     * Sets the value of the valorPis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorPis(BigDecimal value) {
        this.valorPis = value;
    }

    /**
     * Gets the value of the aliquotaCofins property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getAliquotaCofins() {
        return aliquotaCofins;
    }

    /**
     * Sets the value of the aliquotaCofins property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaCofins(BigDecimal value) {
        this.aliquotaCofins = value;
    }

    /**
     * Gets the value of the retidoCofins property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getRetidoCofins() {
        return retidoCofins;
    }

    /**
     * Sets the value of the retidoCofins property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoCofins(Byte value) {
        this.retidoCofins = value;
    }

    /**
     * Gets the value of the valorCofins property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getValorCofins() {
        return valorCofins;
    }

    /**
     * Sets the value of the valorCofins property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorCofins(BigDecimal value) {
        this.valorCofins = value;
    }

    /**
     * Gets the value of the aliquotaInss property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getAliquotaInss() {
        return aliquotaInss;
    }

    /**
     * Sets the value of the aliquotaInss property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaInss(BigDecimal value) {
        this.aliquotaInss = value;
    }

    /**
     * Gets the value of the retidoInss property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getRetidoInss() {
        return retidoInss;
    }

    /**
     * Sets the value of the retidoInss property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoInss(Byte value) {
        this.retidoInss = value;
    }

    /**
     * Gets the value of the valorInss property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getValorInss() {
        return valorInss;
    }

    /**
     * Sets the value of the valorInss property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorInss(BigDecimal value) {
        this.valorInss = value;
    }

    /**
     * Gets the value of the aliquotaIr property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getAliquotaIr() {
        return aliquotaIr;
    }

    /**
     * Sets the value of the aliquotaIr property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaIr(BigDecimal value) {
        this.aliquotaIr = value;
    }

    /**
     * Gets the value of the retidoIr property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getRetidoIr() {
        return retidoIr;
    }

    /**
     * Sets the value of the retidoIr property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoIr(Byte value) {
        this.retidoIr = value;
    }

    /**
     * Gets the value of the valorIr property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getValorIr() {
        return valorIr;
    }

    /**
     * Sets the value of the valorIr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorIr(BigDecimal value) {
        this.valorIr = value;
    }

    /**
     * Gets the value of the aliquotaCsll property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getAliquotaCsll() {
        return aliquotaCsll;
    }

    /**
     * Sets the value of the aliquotaCsll property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaCsll(BigDecimal value) {
        this.aliquotaCsll = value;
    }

    /**
     * Gets the value of the retidoCsll property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getRetidoCsll() {
        return retidoCsll;
    }

    /**
     * Sets the value of the retidoCsll property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoCsll(Byte value) {
        this.retidoCsll = value;
    }

    /**
     * Gets the value of the valorCsll property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getValorCsll() {
        return valorCsll;
    }

    /**
     * Sets the value of the valorCsll property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setValorCsll(BigDecimal value) {
        this.valorCsll = value;
    }

    /**
     * Gets the value of the aliquotaCpp property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getAliquotaCpp() {
        return aliquotaCpp;
    }

    /**
     * Sets the value of the aliquotaCpp property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaCpp(BigDecimal value) {
        this.aliquotaCpp = value;
    }

    /**
     * Gets the value of the retidoCpp property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getRetidoCpp() {
        return retidoCpp;
    }

    /**
     * Sets the value of the retidoCpp property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoCpp(Byte value) {
        this.retidoCpp = value;
    }

    /**
     * Gets the value of the valorCpp property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getValorCpp() {
        return valorCpp;
    }

    /**
     * Sets the value of the valorCpp property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setValorCpp(BigDecimal value) {
        this.valorCpp = value;
    }

    /**
     * Gets the value of the outrasRetencoes property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getOutrasRetencoes() {
        return outrasRetencoes;
    }

    /**
     * Sets the value of the outrasRetencoes property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setOutrasRetencoes(BigDecimal value) {
        this.outrasRetencoes = value;
    }

    /**
     * Gets the value of the retidoOutrasRetencoes property.
     *
     * @return
     *     possible object is
     *     {@link Byte }
     *
     */
    public Byte getRetidoOutrasRetencoes() {
        return retidoOutrasRetencoes;
    }

    /**
     * Sets the value of the retidoOutrasRetencoes property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setRetidoOutrasRetencoes(Byte value) {
        this.retidoOutrasRetencoes = value;
    }

    /**
     * Gets the value of the aliquotaTotTributos property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getAliquotaTotTributos() {
        return aliquotaTotTributos;
    }

    /**
     * Sets the value of the aliquotaTotTributos property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setAliquotaTotTributos(BigDecimal value) {
        this.aliquotaTotTributos = value;
    }

    /**
     * Gets the value of the valTotTributos property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getValTotTributos() {
        return valTotTributos;
    }

    /**
     * Sets the value of the valTotTributos property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setValTotTributos(BigDecimal value) {
        this.valTotTributos = value;
    }

    /**
     * Gets the value of the valorIss property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getValorIss() {
        return valorIss;
    }

    /**
     * Sets the value of the valorIss property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setValorIss(BigDecimal value) {
        this.valorIss = value;
    }

    /**
     * Gets the value of the aliquota property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquota() {
        return aliquota;
    }

    /**
     * Sets the value of the aliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquota(BigDecimal value) {
        this.aliquota = value;
    }

    /**
     * Gets the value of the descontoIncondicionado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDescontoIncondicionado() {
        return descontoIncondicionado;
    }

    /**
     * Sets the value of the descontoIncondicionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDescontoIncondicionado(BigDecimal value) {
        this.descontoIncondicionado = value;
    }

    /**
     * Gets the value of the descontoCondicionado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDescontoCondicionado() {
        return descontoCondicionado;
    }

    /**
     * Sets the value of the descontoCondicionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDescontoCondicionado(BigDecimal value) {
        this.descontoCondicionado = value;
    }

}
