//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 03:55:13 PM BRT 
//


package br.com.webpublico.domain.dto.nfse203;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tsUnidade.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tsUnidade">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UN"/>
 *     &lt;enumeration value="HS"/>
 *     &lt;enumeration value="M2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tsUnidade")
@XmlEnum
public enum TsUnidade {

    UN("UN"),
    HS("HS"),
    @XmlEnumValue("M2")
    M_2("M2");
    private final String value;

    TsUnidade(String v) {
        value = v;
    }

    public static br.com.webpublico.domain.dto.nfse203.TsUnidade fromValue(String v) {
        for (br.com.webpublico.domain.dto.nfse203.TsUnidade c: br.com.webpublico.domain.dto.nfse203.TsUnidade.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
