//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.ListaMensagemRetorno;
import br.com.webpublico.domain.dto.nfse12.TcRetCancelamento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcRetCancelamento"/>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}ListaMensagemRetorno"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tcRetCancelamento",
    "listaMensagemRetorno"
})
@XmlRootElement(name = "CancelarNfseResposta")
public class CancelarNfseResposta {

    protected TcRetCancelamento tcRetCancelamento;
    @XmlElement(name = "ListaMensagemRetorno")
    protected ListaMensagemRetorno listaMensagemRetorno;

    /**
     * Gets the value of the tcRetCancelamento property.
     *
     * @return
     *     possible object is
     *     {@link TcRetCancelamento }
     *
     */
    public TcRetCancelamento getTcRetCancelamento() {
        return tcRetCancelamento;
    }

    /**
     * Sets the value of the tcRetCancelamento property.
     *
     * @param value
     *     allowed object is
     *     {@link TcRetCancelamento }
     *     
     */
    public void setTcRetCancelamento(TcRetCancelamento value) {
        this.tcRetCancelamento = value;
    }

    /**
     * Gets the value of the listaMensagemRetorno property.
     * 
     * @return
     *     possible object is
     *     {@link ListaMensagemRetorno }
     *     
     */
    public ListaMensagemRetorno getListaMensagemRetorno() {
        return listaMensagemRetorno;
    }

    /**
     * Sets the value of the listaMensagemRetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaMensagemRetorno }
     *     
     */
    public void setListaMensagemRetorno(ListaMensagemRetorno value) {
        this.listaMensagemRetorno = value;
    }

}
