//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoIntermediario;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoPrestador;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoRequerente;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoRequerente" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcIdentificacaoRequerente"/>
 *         &lt;element name="NumeroNfse" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsNumeroNfse" minOccurs="0"/>
 *         &lt;element name="PeriodoEmissao" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataInicial" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsData"/>
 *                   &lt;element name="DataFinal" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsData"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IdentificacaoPrestador" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcIdentificacaoPrestador" minOccurs="0"/>
 *         &lt;element name="IdentificacaoIntermediario" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcIdentificacaoIntermediario" minOccurs="0"/>
 *         &lt;element name="Pagina" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsPagina"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identificacaoRequerente",
    "numeroNfse",
    "periodoEmissao",
    "identificacaoPrestador",
    "identificacaoIntermediario",
    "pagina"
})
@XmlRootElement(name = "ConsultarNfseServicoTomadoEnvio")
public class ConsultarNfseServicoTomadoEnvio {

    @XmlElement(name = "IdentificacaoRequerente", required = true)
    protected TcIdentificacaoRequerente identificacaoRequerente;
    @XmlElement(name = "NumeroNfse")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroNfse;
    @XmlElement(name = "PeriodoEmissao")
    protected br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoEnvio.PeriodoEmissao periodoEmissao;
    @XmlElement(name = "IdentificacaoPrestador")
    protected TcIdentificacaoPrestador identificacaoPrestador;
    @XmlElement(name = "IdentificacaoIntermediario")
    protected TcIdentificacaoIntermediario identificacaoIntermediario;
    @XmlElement(name = "Pagina")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int pagina;

    /**
     * Gets the value of the identificacaoRequerente property.
     *
     * @return
     *     possible object is
     *     {@link TcIdentificacaoRequerente }
     *
     */
    public TcIdentificacaoRequerente getIdentificacaoRequerente() {
        return identificacaoRequerente;
    }

    /**
     * Sets the value of the identificacaoRequerente property.
     *
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoRequerente }
     *
     */
    public void setIdentificacaoRequerente(TcIdentificacaoRequerente value) {
        this.identificacaoRequerente = value;
    }

    /**
     * Gets the value of the numeroNfse property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNumeroNfse() {
        return numeroNfse;
    }

    /**
     * Sets the value of the numeroNfse property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNumeroNfse(BigInteger value) {
        this.numeroNfse = value;
    }

    /**
     * Gets the value of the periodoEmissao property.
     *
     * @return
     *     possible object is
     *     {@link br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoEnvio.PeriodoEmissao }
     *
     */
    public br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoEnvio.PeriodoEmissao getPeriodoEmissao() {
        return periodoEmissao;
    }

    /**
     * Sets the value of the periodoEmissao property.
     *
     * @param value
     *     allowed object is
     *     {@link br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoEnvio.PeriodoEmissao }
     *
     */
    public void setPeriodoEmissao(br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoEnvio.PeriodoEmissao value) {
        this.periodoEmissao = value;
    }

    /**
     * Gets the value of the identificacaoPrestador property.
     *
     * @return
     *     possible object is
     *     {@link TcIdentificacaoPrestador }
     *
     */
    public TcIdentificacaoPrestador getIdentificacaoPrestador() {
        return identificacaoPrestador;
    }

    /**
     * Sets the value of the identificacaoPrestador property.
     *
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoPrestador }
     *     
     */
    public void setIdentificacaoPrestador(TcIdentificacaoPrestador value) {
        this.identificacaoPrestador = value;
    }

    /**
     * Gets the value of the identificacaoIntermediario property.
     * 
     * @return
     *     possible object is
     *     {@link TcIdentificacaoIntermediario }
     *     
     */
    public TcIdentificacaoIntermediario getIdentificacaoIntermediario() {
        return identificacaoIntermediario;
    }

    /**
     * Sets the value of the identificacaoIntermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoIntermediario }
     *     
     */
    public void setIdentificacaoIntermediario(TcIdentificacaoIntermediario value) {
        this.identificacaoIntermediario = value;
    }

    /**
     * Gets the value of the pagina property.
     * 
     */
    public int getPagina() {
        return pagina;
    }

    /**
     * Sets the value of the pagina property.
     * 
     */
    public void setPagina(int value) {
        this.pagina = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataInicial" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsData"/>
     *         &lt;element name="DataFinal" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsData"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataInicial",
        "dataFinal"
    })
    public static class PeriodoEmissao {

        @XmlElement(name = "DataInicial", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataInicial;
        @XmlElement(name = "DataFinal", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataFinal;

        /**
         * Gets the value of the dataInicial property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataInicial() {
            return dataInicial;
        }

        /**
         * Sets the value of the dataInicial property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataInicial(XMLGregorianCalendar value) {
            this.dataInicial = value;
        }

        /**
         * Gets the value of the dataFinal property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataFinal() {
            return dataFinal;
        }

        /**
         * Sets the value of the dataFinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataFinal(XMLGregorianCalendar value) {
            this.dataFinal = value;
        }

    }

}
