//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.CancelarNfseEnvio;
import br.com.webpublico.domain.dto.nfse12.CancelarNfseResposta;
import br.com.webpublico.domain.dto.nfse12.ConsultarLoteRpsEnvio;
import br.com.webpublico.domain.dto.nfse12.ConsultarLoteRpsResposta;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseFaixaEnvio;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseFaixaResposta;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseRpsEnvio;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseRpsResposta;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoPrestadoEnvio;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoPrestadoResposta;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoEnvio;
import br.com.webpublico.domain.dto.nfse12.ConsultarNfseServicoTomadoResposta;
import br.com.webpublico.domain.dto.nfse12.EnviarLoteRpsEnvio;
import br.com.webpublico.domain.dto.nfse12.EnviarLoteRpsResposta;
import br.com.webpublico.domain.dto.nfse12.EnviarLoteRpsSincronoEnvio;
import br.com.webpublico.domain.dto.nfse12.EnviarLoteRpsSincronoResposta;
import br.com.webpublico.domain.dto.nfse12.ListaMensagemAlertaRetorno;
import br.com.webpublico.domain.dto.nfse12.ListaMensagemRetorno;
import br.com.webpublico.domain.dto.nfse12.ListaMensagemRetornoLote;
import br.com.webpublico.domain.dto.nfse12.SubstituirNfseEnvio;
import br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta;
import br.com.webpublico.domain.dto.nfse12.TcCancelamentoNfse;
import br.com.webpublico.domain.dto.nfse12.TcCompNfse;
import br.com.webpublico.domain.dto.nfse12.TcConfirmacaoCancelamento;
import br.com.webpublico.domain.dto.nfse12.TcContato;
import br.com.webpublico.domain.dto.nfse12.TcCpfCnpj;
import br.com.webpublico.domain.dto.nfse12.TcDadosDeducao;
import br.com.webpublico.domain.dto.nfse12.TcDadosIntermediario;
import br.com.webpublico.domain.dto.nfse12.TcDadosPrestador;
import br.com.webpublico.domain.dto.nfse12.TcDadosTomador;
import br.com.webpublico.domain.dto.nfse12.TcDeclaracaoPrestacaoServico;
import br.com.webpublico.domain.dto.nfse12.TcEndereco;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoOrgaoGerador;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoPrestador;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoRequerente;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoRps;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoTomador;
import br.com.webpublico.domain.dto.nfse12.TcInfDeclaracaoPrestacaoServico;
import br.com.webpublico.domain.dto.nfse12.TcInfNfse;
import br.com.webpublico.domain.dto.nfse12.TcInfPedidoCancelamento;
import br.com.webpublico.domain.dto.nfse12.TcInfRps;
import br.com.webpublico.domain.dto.nfse12.TcInfSubstituicaoNfse;
import br.com.webpublico.domain.dto.nfse12.TcItemServico;
import br.com.webpublico.domain.dto.nfse12.TcLoteRps;
import br.com.webpublico.domain.dto.nfse12.TcMensagemRetorno;
import br.com.webpublico.domain.dto.nfse12.TcMensagemRetornoLote;
import br.com.webpublico.domain.dto.nfse12.TcNfse;
import br.com.webpublico.domain.dto.nfse12.TcPedidoCancelamento;
import br.com.webpublico.domain.dto.nfse12.TcRetCancelamento;
import br.com.webpublico.domain.dto.nfse12.TcSubstituicaoNfse;
import br.com.webpublico.domain.dto.nfse12.TcValoresDeclaracaoServico;
import br.com.webpublico.domain.dto.nfse12.TcValoresNfse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.webpublico package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CompNfse_QNAME = new QName("http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", "CompNfse");
    private final static QName _Nfse_QNAME = new QName("http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", "Nfse");
    private final static QName _NfseSubstituicao_QNAME = new QName("http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", "NfseSubstituicao");
    private final static QName _NfseCancelamento_QNAME = new QName("http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", "NfseCancelamento");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.webpublico
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarNfseFaixaEnvio }
     *
     */
    public ConsultarNfseFaixaEnvio createConsultarNfseFaixaEnvio() {
        return new ConsultarNfseFaixaEnvio();
    }

    /**
     * Create an instance of {@link ConsultarNfseFaixaResposta }
     *
     */
    public ConsultarNfseFaixaResposta createConsultarNfseFaixaResposta() {
        return new ConsultarNfseFaixaResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoTomadoEnvio }
     *
     */
    public ConsultarNfseServicoTomadoEnvio createConsultarNfseServicoTomadoEnvio() {
        return new ConsultarNfseServicoTomadoEnvio();
    }

    /**
     * Create an instance of {@link SubstituirNfseResposta }
     *
     */
    public SubstituirNfseResposta createSubstituirNfseResposta() {
        return new SubstituirNfseResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoTomadoResposta }
     *
     */
    public ConsultarNfseServicoTomadoResposta createConsultarNfseServicoTomadoResposta() {
        return new ConsultarNfseServicoTomadoResposta();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsSincronoResposta }
     *
     */
    public EnviarLoteRpsSincronoResposta createEnviarLoteRpsSincronoResposta() {
        return new EnviarLoteRpsSincronoResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoPrestadoResposta }
     *
     */
    public ConsultarNfseServicoPrestadoResposta createConsultarNfseServicoPrestadoResposta() {
        return new ConsultarNfseServicoPrestadoResposta();
    }

    /**
     * Create an instance of {@link ConsultarLoteRpsResposta }
     *
     */
    public ConsultarLoteRpsResposta createConsultarLoteRpsResposta() {
        return new ConsultarLoteRpsResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoPrestadoEnvio }
     *
     */
    public ConsultarNfseServicoPrestadoEnvio createConsultarNfseServicoPrestadoEnvio() {
        return new ConsultarNfseServicoPrestadoEnvio();
    }

    /**
     * Create an instance of {@link TcDadosServico }
     *
     */
    public TcDadosServico createTcDadosServico() {
        return new TcDadosServico();
    }

    /**
     * Create an instance of {@link SubstituirNfseResposta.RetSubstituicao }
     *
     */
    public SubstituirNfseResposta.RetSubstituicao createSubstituirNfseRespostaRetSubstituicao() {
        return new SubstituirNfseResposta.RetSubstituicao();
    }

    /**
     * Create an instance of {@link TcLoteRps }
     *
     */
    public TcLoteRps createTcLoteRps() {
        return new TcLoteRps();
    }

    /**
     * Create an instance of {@link CancelarNfseEnvio }
     *
     */
    public CancelarNfseEnvio createCancelarNfseEnvio() {
        return new CancelarNfseEnvio();
    }

    /**
     * Create an instance of {@link TcIdentificacaoRequerente }
     *
     */
    public TcIdentificacaoRequerente createTcIdentificacaoRequerente() {
        return new TcIdentificacaoRequerente();
    }

    /**
     * Create an instance of {@link TcPedidoCancelamento }
     *
     */
    public TcPedidoCancelamento createTcPedidoCancelamento() {
        return new TcPedidoCancelamento();
    }

    /**
     * Create an instance of {@link ConsultarNfseFaixaEnvio.Faixa }
     *
     */
    public ConsultarNfseFaixaEnvio.Faixa createConsultarNfseFaixaEnvioFaixa() {
        return new ConsultarNfseFaixaEnvio.Faixa();
    }

    /**
     * Create an instance of {@link ConsultarNfseFaixaResposta.ListaConsultaNfse }
     *
     */
    public ConsultarNfseFaixaResposta.ListaConsultaNfse createConsultarNfseFaixaRespostaListaConsultaNfse() {
        return new ConsultarNfseFaixaResposta.ListaConsultaNfse();
    }

    /**
     * Create an instance of {@link ListaMensagemRetorno }
     *
     */
    public ListaMensagemRetorno createListaMensagemRetorno() {
        return new ListaMensagemRetorno();
    }

    /**
     * Create an instance of {@link TcMensagemRetorno }
     *
     */
    public TcMensagemRetorno createTcMensagemRetorno() {
        return new TcMensagemRetorno();
    }

    /**
     * Create an instance of {@link TcCompNfse }
     *
     */
    public TcCompNfse createTcCompNfse() {
        return new TcCompNfse();
    }

    /**
     * Create an instance of {@link ListaMensagemAlertaRetorno }
     *
     */
    public ListaMensagemAlertaRetorno createListaMensagemAlertaRetorno() {
        return new ListaMensagemAlertaRetorno();
    }

    /**
     * Create an instance of {@link TcSubstituicaoNfse }
     *
     */
    public TcSubstituicaoNfse createTcSubstituicaoNfse() {
        return new TcSubstituicaoNfse();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsEnvio }
     *
     */
    public EnviarLoteRpsEnvio createEnviarLoteRpsEnvio() {
        return new EnviarLoteRpsEnvio();
    }

    /**
     * Create an instance of {@link TcNfse }
     *
     */
    public TcNfse createTcNfse() {
        return new TcNfse();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoTomadoEnvio.PeriodoEmissao }
     *
     */
    public ConsultarNfseServicoTomadoEnvio.PeriodoEmissao createConsultarNfseServicoTomadoEnvioPeriodoEmissao() {
        return new ConsultarNfseServicoTomadoEnvio.PeriodoEmissao();
    }

    /**
     * Create an instance of {@link TcIdentificacaoPrestador }
     *
     */
    public TcIdentificacaoPrestador createTcIdentificacaoPrestador() {
        return new TcIdentificacaoPrestador();
    }

    /**
     * Create an instance of {@link TcIdentificacaoIntermediario }
     *
     */
    public TcIdentificacaoIntermediario createTcIdentificacaoIntermediario() {
        return new TcIdentificacaoIntermediario();
    }

    /**
     * Create an instance of {@link SubstituirNfseEnvio }
     *
     */
    public SubstituirNfseEnvio createSubstituirNfseEnvio() {
        return new SubstituirNfseEnvio();
    }

    /**
     * Create an instance of {@link TcDeclaracaoPrestacaoServico }
     *
     */
    public TcDeclaracaoPrestacaoServico createTcDeclaracaoPrestacaoServico() {
        return new TcDeclaracaoPrestacaoServico();
    }

    /**
     * Create an instance of {@link TcCancelamentoNfse }
     *
     */
    public TcCancelamentoNfse createTcCancelamentoNfse() {
        return new TcCancelamentoNfse();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsResposta }
     *
     */
    public EnviarLoteRpsResposta createEnviarLoteRpsResposta() {
        return new EnviarLoteRpsResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoTomadoResposta.ListaConsultaNfse }
     *
     */
    public ConsultarNfseServicoTomadoResposta.ListaConsultaNfse createConsultarNfseServicoTomadoRespostaListaConsultaNfse() {
        return new ConsultarNfseServicoTomadoResposta.ListaConsultaNfse();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsSincronoResposta.ListaNfse }
     *
     */
    public EnviarLoteRpsSincronoResposta.ListaNfse createEnviarLoteRpsSincronoRespostaListaNfse() {
        return new EnviarLoteRpsSincronoResposta.ListaNfse();
    }

    /**
     * Create an instance of {@link ListaMensagemRetornoLote }
     *
     */
    public ListaMensagemRetornoLote createListaMensagemRetornoLote() {
        return new ListaMensagemRetornoLote();
    }

    /**
     * Create an instance of {@link TcMensagemRetornoLote }
     *
     */
    public TcMensagemRetornoLote createTcMensagemRetornoLote() {
        return new TcMensagemRetornoLote();
    }

    /**
     * Create an instance of {@link ConsultarNfseRpsEnvio }
     *
     */
    public ConsultarNfseRpsEnvio createConsultarNfseRpsEnvio() {
        return new ConsultarNfseRpsEnvio();
    }

    /**
     * Create an instance of {@link TcIdentificacaoRps }
     *
     */
    public TcIdentificacaoRps createTcIdentificacaoRps() {
        return new TcIdentificacaoRps();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoPrestadoResposta.ListaConsultaNfse }
     *
     */
    public ConsultarNfseServicoPrestadoResposta.ListaConsultaNfse createConsultarNfseServicoPrestadoRespostaListaConsultaNfse() {
        return new ConsultarNfseServicoPrestadoResposta.ListaConsultaNfse();
    }

    /**
     * Create an instance of {@link CancelarNfseResposta }
     *
     */
    public CancelarNfseResposta createCancelarNfseResposta() {
        return new CancelarNfseResposta();
    }

    /**
     * Create an instance of {@link TcRetCancelamento }
     *
     */
    public TcRetCancelamento createTcRetCancelamento() {
        return new TcRetCancelamento();
    }

    /**
     * Create an instance of {@link ConsultarLoteRpsResposta.ListaNfse }
     *
     */
    public ConsultarLoteRpsResposta.ListaNfse createConsultarLoteRpsRespostaListaNfse() {
        return new ConsultarLoteRpsResposta.ListaNfse();
    }

    /**
     * Create an instance of {@link ConsultarNfseRpsResposta }
     *
     */
    public ConsultarNfseRpsResposta createConsultarNfseRpsResposta() {
        return new ConsultarNfseRpsResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseServicoPrestadoEnvio.PeriodoEmissao }
     *
     */
    public ConsultarNfseServicoPrestadoEnvio.PeriodoEmissao createConsultarNfseServicoPrestadoEnvioPeriodoEmissao() {
        return new ConsultarNfseServicoPrestadoEnvio.PeriodoEmissao();
    }

    /**
     * Create an instance of {@link TcIdentificacaoTomador }
     *
     */
    public TcIdentificacaoTomador createTcIdentificacaoTomador() {
        return new TcIdentificacaoTomador();
    }

    /**
     * Create an instance of {@link ConsultarLoteRpsEnvio }
     *
     */
    public ConsultarLoteRpsEnvio createConsultarLoteRpsEnvio() {
        return new ConsultarLoteRpsEnvio();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsSincronoEnvio }
     *
     */
    public EnviarLoteRpsSincronoEnvio createEnviarLoteRpsSincronoEnvio() {
        return new EnviarLoteRpsSincronoEnvio();
    }

    /**
     * Create an instance of {@link TcInfPedidoCancelamento }
     *
     */
    public TcInfPedidoCancelamento createTcInfPedidoCancelamento() {
        return new TcInfPedidoCancelamento();
    }

    /**
     * Create an instance of {@link TcDadosDeducao }
     *
     */
    public TcDadosDeducao createTcDadosDeducao() {
        return new TcDadosDeducao();
    }

    /**
     * Create an instance of {@link TcEndereco }
     *
     */
    public TcEndereco createTcEndereco() {
        return new TcEndereco();
    }

    /**
     * Create an instance of {@link TcInfNfse }
     *
     */
    public TcInfNfse createTcInfNfse() {
        return new TcInfNfse();
    }

    /**
     * Create an instance of {@link TcValoresDeclaracaoServico }
     *
     */
    public TcValoresDeclaracaoServico createTcValoresDeclaracaoServico() {
        return new TcValoresDeclaracaoServico();
    }

    /**
     * Create an instance of {@link TcDadosConstrucaoCivil }
     *
     */
    public TcDadosConstrucaoCivil createTcDadosConstrucaoCivil() {
        return new TcDadosConstrucaoCivil();
    }

    /**
     * Create an instance of {@link TcDadosPrestador }
     *
     */
    public TcDadosPrestador createTcDadosPrestador() {
        return new TcDadosPrestador();
    }

    /**
     * Create an instance of {@link TcValoresNfse }
     *
     */
    public TcValoresNfse createTcValoresNfse() {
        return new TcValoresNfse();
    }

    /**
     * Create an instance of {@link TcContato }
     *
     */
    public TcContato createTcContato() {
        return new TcContato();
    }

    /**
     * Create an instance of {@link TcInfRps }
     *
     */
    public TcInfRps createTcInfRps() {
        return new TcInfRps();
    }

    /**
     * Create an instance of {@link TcInfDeclaracaoPrestacaoServico }
     *
     */
    public TcInfDeclaracaoPrestacaoServico createTcInfDeclaracaoPrestacaoServico() {
        return new TcInfDeclaracaoPrestacaoServico();
    }

    /**
     * Create an instance of {@link TcItemServico }
     *
     */
    public TcItemServico createTcItemServico() {
        return new TcItemServico();
    }

    /**
     * Create an instance of {@link TcDadosTomador }
     *
     */
    public TcDadosTomador createTcDadosTomador() {
        return new TcDadosTomador();
    }

    /**
     * Create an instance of {@link TcInfSubstituicaoNfse }
     *
     */
    public TcInfSubstituicaoNfse createTcInfSubstituicaoNfse() {
        return new TcInfSubstituicaoNfse();
    }

    /**
     * Create an instance of {@link TcCpfCnpj }
     *
     */
    public TcCpfCnpj createTcCpfCnpj() {
        return new TcCpfCnpj();
    }

    /**
     * Create an instance of {@link TcDadosIntermediario }
     *
     */
    public TcDadosIntermediario createTcDadosIntermediario() {
        return new TcDadosIntermediario();
    }

    /**
     * Create an instance of {@link TcIdentificacaoOrgaoGerador }
     *
     */
    public TcIdentificacaoOrgaoGerador createTcIdentificacaoOrgaoGerador() {
        return new TcIdentificacaoOrgaoGerador();
    }

    /**
     * Create an instance of {@link TcConfirmacaoCancelamento }
     *
     */
    public TcConfirmacaoCancelamento createTcConfirmacaoCancelamento() {
        return new TcConfirmacaoCancelamento();
    }

    /**
     * Create an instance of {@link TcDadosServico.ListaItensServico }
     *
     */
    public TcDadosServico.ListaItensServico createTcDadosServicoListaItensServico() {
        return new TcDadosServico.ListaItensServico();
    }

    /**
     * Create an instance of {@link SubstituirNfseResposta.RetSubstituicao.NfseSubstituida }
     *
     */
    public SubstituirNfseResposta.RetSubstituicao.NfseSubstituida createSubstituirNfseRespostaRetSubstituicaoNfseSubstituida() {
        return new SubstituirNfseResposta.RetSubstituicao.NfseSubstituida();
    }

    /**
     * Create an instance of {@link SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora }
     *
     */
    public SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora createSubstituirNfseRespostaRetSubstituicaoNfseSubstituidora() {
        return new SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora();
    }

    /**
     * Create an instance of {@link TcLoteRps.ListaRps }
     *
     */
    public TcLoteRps.ListaRps createTcLoteRpsListaRps() {
        return new TcLoteRps.ListaRps();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TcCompNfse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", name = "CompNfse")
    public JAXBElement<TcCompNfse> createCompNfse(TcCompNfse value) {
        return new JAXBElement<TcCompNfse>(_CompNfse_QNAME, TcCompNfse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TcNfse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", name = "Nfse")
    public JAXBElement<TcNfse> createNfse(TcNfse value) {
        return new JAXBElement<TcNfse>(_Nfse_QNAME, TcNfse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TcSubstituicaoNfse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", name = "NfseSubstituicao")
    public JAXBElement<TcSubstituicaoNfse> createNfseSubstituicao(TcSubstituicaoNfse value) {
        return new JAXBElement<TcSubstituicaoNfse>(_NfseSubstituicao_QNAME, TcSubstituicaoNfse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TcCancelamentoNfse }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", name = "NfseCancelamento")
    public JAXBElement<TcCancelamentoNfse> createNfseCancelamento(TcCancelamentoNfse value) {
        return new JAXBElement<TcCancelamentoNfse>(_NfseCancelamento_QNAME, TcCancelamentoNfse.class, null, value);
    }

}
