//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.webpublico.domain.dto.nfse12;
