//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.TcDeclaracaoPrestacaoServico;
import br.com.webpublico.domain.dto.nfse12.TcIdentificacaoRequerente;
import br.com.webpublico.domain.dto.nfse12.TcPedidoCancelamento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoRequerente" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcIdentificacaoRequerente"/>
 *         &lt;element name="Pedido" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcPedidoCancelamento"/>
 *         &lt;element name="DeclaracaoPrestacaoServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcDeclaracaoPrestacaoServico"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identificacaoRequerente",
    "pedido",
    "declaracaoPrestacaoServico"
})
@XmlRootElement(name = "SubstituirNfseEnvio")
public class SubstituirNfseEnvio {

    @XmlElement(name = "IdentificacaoRequerente", required = true)
    protected TcIdentificacaoRequerente identificacaoRequerente;
    @XmlElement(name = "Pedido", required = true)
    protected TcPedidoCancelamento pedido;
    @XmlElement(name = "DeclaracaoPrestacaoServico", required = true)
    protected TcDeclaracaoPrestacaoServico declaracaoPrestacaoServico;

    /**
     * Gets the value of the identificacaoRequerente property.
     *
     * @return
     *     possible object is
     *     {@link TcIdentificacaoRequerente }
     *
     */
    public TcIdentificacaoRequerente getIdentificacaoRequerente() {
        return identificacaoRequerente;
    }

    /**
     * Sets the value of the identificacaoRequerente property.
     *
     * @param value
     *     allowed object is
     *     {@link TcIdentificacaoRequerente }
     *
     */
    public void setIdentificacaoRequerente(TcIdentificacaoRequerente value) {
        this.identificacaoRequerente = value;
    }

    /**
     * Gets the value of the pedido property.
     *
     * @return
     *     possible object is
     *     {@link TcPedidoCancelamento }
     *
     */
    public TcPedidoCancelamento getPedido() {
        return pedido;
    }

    /**
     * Sets the value of the pedido property.
     *
     * @param value
     *     allowed object is
     *     {@link TcPedidoCancelamento }
     *
     */
    public void setPedido(TcPedidoCancelamento value) {
        this.pedido = value;
    }

    /**
     * Gets the value of the declaracaoPrestacaoServico property.
     *
     * @return
     *     possible object is
     *     {@link TcDeclaracaoPrestacaoServico }
     *
     */
    public TcDeclaracaoPrestacaoServico getDeclaracaoPrestacaoServico() {
        return declaracaoPrestacaoServico;
    }

    /**
     * Sets the value of the declaracaoPrestacaoServico property.
     *
     * @param value
     *     allowed object is
     *     {@link TcDeclaracaoPrestacaoServico }
     *     
     */
    public void setDeclaracaoPrestacaoServico(TcDeclaracaoPrestacaoServico value) {
        this.declaracaoPrestacaoServico = value;
    }

}
