//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.ListaMensagemRetorno;
import br.com.webpublico.domain.dto.nfse12.TcCompNfse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="RetSubstituicao">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NfseSubstituida">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}CompNfse"/>
 *                             &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}ListaMensagemRetorno" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="NfseSubstituidora">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}CompNfse"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}ListaMensagemRetorno"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retSubstituicao",
    "listaMensagemRetorno"
})
@XmlRootElement(name = "SubstituirNfseResposta")
public class SubstituirNfseResposta {

    @XmlElement(name = "RetSubstituicao")
    protected br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao retSubstituicao;
    @XmlElement(name = "ListaMensagemRetorno")
    protected ListaMensagemRetorno listaMensagemRetorno;

    /**
     * Gets the value of the retSubstituicao property.
     *
     * @return
     *     possible object is
     *     {@link br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao }
     *
     */
    public br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao getRetSubstituicao() {
        return retSubstituicao;
    }

    /**
     * Sets the value of the retSubstituicao property.
     *
     * @param value
     *     allowed object is
     *     {@link br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao }
     *
     */
    public void setRetSubstituicao(br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao value) {
        this.retSubstituicao = value;
    }

    /**
     * Gets the value of the listaMensagemRetorno property.
     *
     * @return
     *     possible object is
     *     {@link ListaMensagemRetorno }
     *
     */
    public ListaMensagemRetorno getListaMensagemRetorno() {
        return listaMensagemRetorno;
    }

    /**
     * Sets the value of the listaMensagemRetorno property.
     *
     * @param value
     *     allowed object is
     *     {@link ListaMensagemRetorno }
     *
     */
    public void setListaMensagemRetorno(ListaMensagemRetorno value) {
        this.listaMensagemRetorno = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NfseSubstituida">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}CompNfse"/>
     *                   &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}ListaMensagemRetorno" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="NfseSubstituidora">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}CompNfse"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nfseSubstituida",
        "nfseSubstituidora"
    })
    public static class RetSubstituicao {

        @XmlElement(name = "NfseSubstituida", required = true)
        protected br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituida nfseSubstituida;
        @XmlElement(name = "NfseSubstituidora", required = true)
        protected br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora nfseSubstituidora;

        /**
         * Gets the value of the nfseSubstituida property.
         *
         * @return
         *     possible object is
         *     {@link br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituida }
         *
         */
        public br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituida getNfseSubstituida() {
            return nfseSubstituida;
        }

        /**
         * Sets the value of the nfseSubstituida property.
         *
         * @param value
         *     allowed object is
         *     {@link br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituida }
         *
         */
        public void setNfseSubstituida(br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituida value) {
            this.nfseSubstituida = value;
        }

        /**
         * Gets the value of the nfseSubstituidora property.
         *
         * @return
         *     possible object is
         *     {@link br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora }
         *
         */
        public br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora getNfseSubstituidora() {
            return nfseSubstituidora;
        }

        /**
         * Sets the value of the nfseSubstituidora property.
         *
         * @param value
         *     allowed object is
         *     {@link br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora }
         *
         */
        public void setNfseSubstituidora(br.com.webpublico.domain.dto.nfse12.SubstituirNfseResposta.RetSubstituicao.NfseSubstituidora value) {
            this.nfseSubstituidora = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}CompNfse"/>
         *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}ListaMensagemRetorno" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "compNfse",
            "listaMensagemRetorno"
        })
        public static class NfseSubstituida {

            @XmlElement(name = "CompNfse", required = true)
            protected TcCompNfse compNfse;
            @XmlElement(name = "ListaMensagemRetorno")
            protected ListaMensagemRetorno listaMensagemRetorno;

            /**
             * Gets the value of the compNfse property.
             *
             * @return
             *     possible object is
             *     {@link TcCompNfse }
             *
             */
            public TcCompNfse getCompNfse() {
                return compNfse;
            }

            /**
             * Sets the value of the compNfse property.
             *
             * @param value
             *     allowed object is
             *     {@link TcCompNfse }
             *
             */
            public void setCompNfse(TcCompNfse value) {
                this.compNfse = value;
            }

            /**
             * Gets the value of the listaMensagemRetorno property.
             *
             * @return
             *     possible object is
             *     {@link ListaMensagemRetorno }
             *
             */
            public ListaMensagemRetorno getListaMensagemRetorno() {
                return listaMensagemRetorno;
            }

            /**
             * Sets the value of the listaMensagemRetorno property.
             *
             * @param value
             *     allowed object is
             *     {@link ListaMensagemRetorno }
             *
             */
            public void setListaMensagemRetorno(ListaMensagemRetorno value) {
                this.listaMensagemRetorno = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}CompNfse"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "compNfse"
        })
        public static class NfseSubstituidora {

            @XmlElement(name = "CompNfse", required = true)
            protected TcCompNfse compNfse;

            /**
             * Gets the value of the compNfse property.
             *
             * @return
             *     possible object is
             *     {@link TcCompNfse }
             *
             */
            public TcCompNfse getCompNfse() {
                return compNfse;
            }

            /**
             * Sets the value of the compNfse property.
             *
             * @param value
             *     allowed object is
             *     {@link TcCompNfse }
             *     
             */
            public void setCompNfse(TcCompNfse value) {
                this.compNfse = value;
            }

        }

    }

}
