//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.TcCancelamentoNfse;
import br.com.webpublico.domain.dto.nfse12.TcNfse;
import br.com.webpublico.domain.dto.nfse12.TcSubstituicaoNfse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcCompNfse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcCompNfse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}Nfse"/>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}NfseCancelamento" minOccurs="0"/>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}NfseSubstituicao" minOccurs="0"/>
 *         &lt;element name="Xml" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsXml" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcCompNfse", propOrder = {
    "nfse",
    "nfseCancelamento",
    "nfseSubstituicao",
    "xml"
})
public class TcCompNfse {

    @XmlElement(name = "Nfse", required = true)
    protected TcNfse nfse;
    @XmlElement(name = "NfseCancelamento")
    protected TcCancelamentoNfse nfseCancelamento;
    @XmlElement(name = "NfseSubstituicao")
    protected TcSubstituicaoNfse nfseSubstituicao;
    @XmlElement(name = "Xml")
    protected String xml;

    /**
     * Gets the value of the nfse property.
     *
     * @return
     *     possible object is
     *     {@link TcNfse }
     *
     */
    public TcNfse getNfse() {
        return nfse;
    }

    /**
     * Sets the value of the nfse property.
     *
     * @param value
     *     allowed object is
     *     {@link TcNfse }
     *
     */
    public void setNfse(TcNfse value) {
        this.nfse = value;
    }

    /**
     * Gets the value of the nfseCancelamento property.
     *
     * @return
     *     possible object is
     *     {@link TcCancelamentoNfse }
     *
     */
    public TcCancelamentoNfse getNfseCancelamento() {
        return nfseCancelamento;
    }

    /**
     * Sets the value of the nfseCancelamento property.
     *
     * @param value
     *     allowed object is
     *     {@link TcCancelamentoNfse }
     *
     */
    public void setNfseCancelamento(TcCancelamentoNfse value) {
        this.nfseCancelamento = value;
    }

    /**
     * Gets the value of the nfseSubstituicao property.
     *
     * @return
     *     possible object is
     *     {@link TcSubstituicaoNfse }
     *
     */
    public TcSubstituicaoNfse getNfseSubstituicao() {
        return nfseSubstituicao;
    }

    /**
     * Sets the value of the nfseSubstituicao property.
     *
     * @param value
     *     allowed object is
     *     {@link TcSubstituicaoNfse }
     *     
     */
    public void setNfseSubstituicao(TcSubstituicaoNfse value) {
        this.nfseSubstituicao = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXml() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXml(String value) {
        this.xml = value;
    }

}
