//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.TcItemServico;
import br.com.webpublico.domain.dto.nfse12.TcValoresDeclaracaoServico;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDadosServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDadosServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Valores" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcValoresDeclaracaoServico"/>
 *         &lt;element name="IssRetido" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsSimNao"/>
 *         &lt;element name="ResponsavelRetencao" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsResponsavelRetencao" minOccurs="0"/>
 *         &lt;element name="Discriminacao" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsDiscriminacao"/>
 *         &lt;element name="CodigoMunicipio" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsCodigoMunicipioIbge"/>
 *         &lt;element name="CodigoPais" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsCodigoPaisBacen" minOccurs="0"/>
 *         &lt;element name="ExigibilidadeISS" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsExigibilidadeISS"/>
 *         &lt;element name="MunicipioIncidencia" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsCodigoMunicipioIbge"/>
 *         &lt;element name="NumeroProcesso" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsNumeroProcesso" minOccurs="0"/>
 *         &lt;element name="ListaItensServico">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ItemServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcItemServico" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDadosServico", propOrder = {
    "valores",
    "issRetido",
    "responsavelRetencao",
    "discriminacao",
    "codigoMunicipio",
    "codigoPais",
    "exigibilidadeISS",
    "municipioIncidencia",
    "numeroProcesso",
    "listaItensServico"
})
public class TcDadosServico {

    @XmlElement(name = "Valores", required = true)
    protected TcValoresDeclaracaoServico valores;
    @XmlElement(name = "IssRetido")
    protected byte issRetido;
    @XmlElement(name = "ResponsavelRetencao")
    protected Byte responsavelRetencao;
    @XmlElement(name = "Discriminacao", required = true)
    protected String discriminacao;
    @XmlElement(name = "CodigoMunicipio")
    protected int codigoMunicipio;
    @XmlElement(name = "CodigoPais")
    protected String codigoPais;
    @XmlElement(name = "ExigibilidadeISS")
    protected byte exigibilidadeISS;
    @XmlElement(name = "MunicipioIncidencia")
    protected int municipioIncidencia;
    @XmlElement(name = "NumeroProcesso")
    protected String numeroProcesso;
    @XmlElement(name = "ListaItensServico", required = true)
    protected br.com.webpublico.domain.dto.nfse12.TcDadosServico.ListaItensServico listaItensServico;

    /**
     * Gets the value of the valores property.
     *
     * @return
     *     possible object is
     *     {@link TcValoresDeclaracaoServico }
     *
     */
    public TcValoresDeclaracaoServico getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     *
     * @param value
     *     allowed object is
     *     {@link TcValoresDeclaracaoServico }
     *
     */
    public void setValores(TcValoresDeclaracaoServico value) {
        this.valores = value;
    }

    /**
     * Gets the value of the issRetido property.
     *
     */
    public byte getIssRetido() {
        return issRetido;
    }

    /**
     * Sets the value of the issRetido property.
     *
     */
    public void setIssRetido(byte value) {
        this.issRetido = value;
    }

    /**
     * Gets the value of the responsavelRetencao property.
     *
     * @return
     *     possible object is
     *     {@link Byte }
     *
     */
    public Byte getResponsavelRetencao() {
        return responsavelRetencao;
    }

    /**
     * Sets the value of the responsavelRetencao property.
     *
     * @param value
     *     allowed object is
     *     {@link Byte }
     *
     */
    public void setResponsavelRetencao(Byte value) {
        this.responsavelRetencao = value;
    }

    /**
     * Gets the value of the discriminacao property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDiscriminacao() {
        return discriminacao;
    }

    /**
     * Sets the value of the discriminacao property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDiscriminacao(String value) {
        this.discriminacao = value;
    }

    /**
     * Gets the value of the codigoMunicipio property.
     *
     */
    public int getCodigoMunicipio() {
        return codigoMunicipio;
    }

    /**
     * Sets the value of the codigoMunicipio property.
     *
     */
    public void setCodigoMunicipio(int value) {
        this.codigoMunicipio = value;
    }

    /**
     * Gets the value of the codigoPais property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodigoPais() {
        return codigoPais;
    }

    /**
     * Sets the value of the codigoPais property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodigoPais(String value) {
        this.codigoPais = value;
    }

    /**
     * Gets the value of the exigibilidadeISS property.
     *
     */
    public byte getExigibilidadeISS() {
        return exigibilidadeISS;
    }

    /**
     * Sets the value of the exigibilidadeISS property.
     *
     */
    public void setExigibilidadeISS(byte value) {
        this.exigibilidadeISS = value;
    }

    /**
     * Gets the value of the municipioIncidencia property.
     *
     */
    public int getMunicipioIncidencia() {
        return municipioIncidencia;
    }

    /**
     * Sets the value of the municipioIncidencia property.
     *
     */
    public void setMunicipioIncidencia(int value) {
        this.municipioIncidencia = value;
    }

    /**
     * Gets the value of the numeroProcesso property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNumeroProcesso() {
        return numeroProcesso;
    }

    /**
     * Sets the value of the numeroProcesso property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNumeroProcesso(String value) {
        this.numeroProcesso = value;
    }

    /**
     * Gets the value of the listaItensServico property.
     *
     * @return
     *     possible object is
     *     {@link br.com.webpublico.domain.dto.nfse12.TcDadosServico.ListaItensServico }
     *
     */
    public br.com.webpublico.domain.dto.nfse12.TcDadosServico.ListaItensServico getListaItensServico() {
        return listaItensServico;
    }

    /**
     * Sets the value of the listaItensServico property.
     *
     * @param value
     *     allowed object is
     *     {@link br.com.webpublico.domain.dto.nfse12.TcDadosServico.ListaItensServico }
     *
     */
    public void setListaItensServico(br.com.webpublico.domain.dto.nfse12.TcDadosServico.ListaItensServico value) {
        this.listaItensServico = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ItemServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcItemServico" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemServico"
    })
    public static class ListaItensServico {

        @XmlElement(name = "ItemServico", required = true)
        protected List<TcItemServico> itemServico;

        /**
         * Gets the value of the itemServico property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the itemServico property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItemServico().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TcItemServico }
         *
         *
         */
        public List<TcItemServico> getItemServico() {
            if (itemServico == null) {
                itemServico = new ArrayList<TcItemServico>();
            }
            return this.itemServico;
        }

    }

}
