//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.TcInfDeclaracaoPrestacaoServico;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDeclaracaoPrestacaoServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDeclaracaoPrestacaoServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfDeclaracaoPrestacaoServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcInfDeclaracaoPrestacaoServico"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDeclaracaoPrestacaoServico", propOrder = {
    "infDeclaracaoPrestacaoServico"
})
public class TcDeclaracaoPrestacaoServico {

    @XmlElement(name = "InfDeclaracaoPrestacaoServico", required = true)
    protected TcInfDeclaracaoPrestacaoServico infDeclaracaoPrestacaoServico;

    /**
     * Gets the value of the infDeclaracaoPrestacaoServico property.
     * 
     * @return
     *     possible object is
     *     {@link TcInfDeclaracaoPrestacaoServico }
     *     
     */
    public TcInfDeclaracaoPrestacaoServico getInfDeclaracaoPrestacaoServico() {
        return infDeclaracaoPrestacaoServico;
    }

    /**
     * Sets the value of the infDeclaracaoPrestacaoServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInfDeclaracaoPrestacaoServico }
     *     
     */
    public void setInfDeclaracaoPrestacaoServico(TcInfDeclaracaoPrestacaoServico value) {
        this.infDeclaracaoPrestacaoServico = value;
    }

}
