//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for tcIdentificacaoRps complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tcIdentificacaoRps">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Numero" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsNumeroRps"/>
 *         &lt;element name="Serie" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsSerieRps"/>
 *         &lt;element name="Tipo" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsTipoRps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcIdentificacaoRps", propOrder = {
        "numero",
        "serie",
        "tipo"
})
public class TcIdentificacaoRps {

    @XmlElement(name = "Numero", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numero;
    @XmlElement(name = "Serie", required = true)
    protected String serie;
    @XmlElement(name = "Tipo")
    protected byte tipo;

    /**
     * Gets the value of the numero property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNumero(BigInteger value) {
        this.numero = value;
    }

    /**
     * Gets the value of the serie property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * Gets the value of the tipo property.
     */
    public byte getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     */
    public void setTipo(byte value) {
        this.tipo = value;
    }

}
