//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 12:43:16 PM BRT 
//


package br.com.webpublico.domain.dto.nfse12;

import br.com.webpublico.domain.dto.nfse12.TcDeclaracaoPrestacaoServico;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcLoteRps complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcLoteRps">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroLote" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsNumeroLote"/>
 *         &lt;element name="QuantidadeRps" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tsQuantidadeRps"/>
 *         &lt;element name="ListaRps">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DeclaracaoPrestacaoServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcDeclaracaoPrestacaoServico" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcLoteRps", propOrder = {
    "numeroLote",
    "quantidadeRps",
    "listaRps"
})
public class TcLoteRps {

    @XmlElement(name = "NumeroLote", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroLote;
    @XmlElement(name = "QuantidadeRps")
    protected int quantidadeRps;
    @XmlElement(name = "ListaRps", required = true)
    protected br.com.webpublico.domain.dto.nfse12.TcLoteRps.ListaRps listaRps;

    /**
     * Gets the value of the numeroLote property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNumeroLote() {
        return numeroLote;
    }

    /**
     * Sets the value of the numeroLote property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNumeroLote(BigInteger value) {
        this.numeroLote = value;
    }

    /**
     * Gets the value of the quantidadeRps property.
     *
     */
    public int getQuantidadeRps() {
        return quantidadeRps;
    }

    /**
     * Sets the value of the quantidadeRps property.
     *
     */
    public void setQuantidadeRps(int value) {
        this.quantidadeRps = value;
    }

    /**
     * Gets the value of the listaRps property.
     *
     * @return
     *     possible object is
     *     {@link br.com.webpublico.domain.dto.nfse12.TcLoteRps.ListaRps }
     *
     */
    public br.com.webpublico.domain.dto.nfse12.TcLoteRps.ListaRps getListaRps() {
        return listaRps;
    }

    /**
     * Sets the value of the listaRps property.
     *
     * @param value
     *     allowed object is
     *     {@link br.com.webpublico.domain.dto.nfse12.TcLoteRps.ListaRps }
     *
     */
    public void setListaRps(br.com.webpublico.domain.dto.nfse12.TcLoteRps.ListaRps value) {
        this.listaRps = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DeclaracaoPrestacaoServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1_2.xsd}tcDeclaracaoPrestacaoServico" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "declaracaoPrestacaoServico"
    })
    public static class ListaRps {

        @XmlElement(name = "DeclaracaoPrestacaoServico", required = true)
        protected List<TcDeclaracaoPrestacaoServico> declaracaoPrestacaoServico;

        /**
         * Gets the value of the declaracaoPrestacaoServico property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the declaracaoPrestacaoServico property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeclaracaoPrestacaoServico().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TcDeclaracaoPrestacaoServico }
         *
         *
         */
        public List<TcDeclaracaoPrestacaoServico> getDeclaracaoPrestacaoServico() {
            if (declaracaoPrestacaoServico == null) {
                declaracaoPrestacaoServico = new ArrayList<TcDeclaracaoPrestacaoServico>();
            }
            return this.declaracaoPrestacaoServico;
        }

    }

}
