//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.01.22 at 01:03:44 PM BRST
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.TcPedidoCancelamento;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pedido" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcPedidoCancelamento"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pedido"
})
@XmlRootElement(name = "CancelarNfseEnvio")
public class CancelarNfseEnvio {

    @XmlElement(name = "Pedido", required = true)
    protected TcPedidoCancelamento pedido;

    /**
     * Gets the value of the pedido property.
     *
     * @return possible object is
     * {@link TcPedidoCancelamento }
     */
    public TcPedidoCancelamento getPedido() {
        return pedido;
    }

    /**
     * Sets the value of the pedido property.
     *
     * @param value allowed object is
     *              {@link TcPedidoCancelamento }
     */
    public void setPedido(TcPedidoCancelamento value) {
        this.pedido = value;
    }

}
