//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 01:03:44 PM BRST 
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.TcIdentificacaoPrestador;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prestador" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcIdentificacaoPrestador"/>
 *         &lt;element name="Protocolo" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsNumeroProtocolo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "prestador",
        "protocolo"
})
@XmlRootElement(name = "ConsultarSituacaoLoteRpsEnvio")
public class ConsultarSituacaoLoteRpsEnvio {

    @XmlElement(name = "Prestador", required = true)
    protected TcIdentificacaoPrestador prestador;
    @XmlElement(name = "Protocolo", required = true)
    protected String protocolo;

    /**
     * Gets the value of the prestador property.
     *
     * @return possible object is
     * {@link TcIdentificacaoPrestador }
     */
    public TcIdentificacaoPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     *
     * @param value allowed object is
     *              {@link TcIdentificacaoPrestador }
     */
    public void setPrestador(TcIdentificacaoPrestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the protocolo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProtocolo() {
        return protocolo;
    }

    /**
     * Sets the value of the protocolo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProtocolo(String value) {
        this.protocolo = value;
    }

}
