//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 01:03:44 PM BRST 
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.TcIdentificacaoPrestador;
import br.com.webpublico.domain.dto.nfse10.TcIdentificacaoRps;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificacaoRps" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcIdentificacaoRps"/>
 *         &lt;element name="Prestador" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcIdentificacaoPrestador"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "identificacaoRps",
        "prestador"
})
@XmlRootElement(name = "ConsultarNfseRpsEnvio")
public class ConsultarNfseRpsEnvio {

    @XmlElement(name = "IdentificacaoRps", required = true)
    protected TcIdentificacaoRps identificacaoRps;
    @XmlElement(name = "Prestador", required = true)
    protected TcIdentificacaoPrestador prestador;

    /**
     * Gets the value of the identificacaoRps property.
     *
     * @return possible object is
     * {@link TcIdentificacaoRps }
     */
    public TcIdentificacaoRps getIdentificacaoRps() {
        return identificacaoRps;
    }

    /**
     * Sets the value of the identificacaoRps property.
     *
     * @param value allowed object is
     *              {@link TcIdentificacaoRps }
     */
    public void setIdentificacaoRps(TcIdentificacaoRps value) {
        this.identificacaoRps = value;
    }

    /**
     * Gets the value of the prestador property.
     *
     * @return possible object is
     * {@link TcIdentificacaoPrestador }
     */
    public TcIdentificacaoPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     *
     * @param value allowed object is
     *              {@link TcIdentificacaoPrestador }
     */
    public void setPrestador(TcIdentificacaoPrestador value) {
        this.prestador = value;
    }

}
