//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 01:03:44 PM BRST 
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.ListaMensagemRetorno;
import br.com.webpublico.domain.dto.nfse10.TcCompNfse;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ListaNfse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1}CompNfse"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1}ListaMensagemRetorno"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "listaNfse",
        "listaMensagemRetorno"
})
@XmlRootElement(name = "ConsultarNfseResposta")
public class ConsultarNfseResposta {

    @XmlElement(name = "ListaNfse")
    protected br.com.webpublico.domain.dto.nfse10.ConsultarNfseResposta.ListaNfse listaNfse;
    @XmlElement(name = "ListaMensagemRetorno")
    protected ListaMensagemRetorno listaMensagemRetorno;

    /**
     * Gets the value of the listaNfse property.
     *
     * @return possible object is
     * {@link br.com.webpublico.domain.dto.nfse10.ConsultarNfseResposta.ListaNfse }
     */
    public br.com.webpublico.domain.dto.nfse10.ConsultarNfseResposta.ListaNfse getListaNfse() {
        return listaNfse;
    }

    /**
     * Sets the value of the listaNfse property.
     *
     * @param value allowed object is
     *              {@link br.com.webpublico.domain.dto.nfse10.ConsultarNfseResposta.ListaNfse }
     */
    public void setListaNfse(br.com.webpublico.domain.dto.nfse10.ConsultarNfseResposta.ListaNfse value) {
        this.listaNfse = value;
    }

    /**
     * Gets the value of the listaMensagemRetorno property.
     *
     * @return possible object is
     * {@link ListaMensagemRetorno }
     */
    public ListaMensagemRetorno getListaMensagemRetorno() {
        return listaMensagemRetorno;
    }

    /**
     * Sets the value of the listaMensagemRetorno property.
     *
     * @param value allowed object is
     *              {@link ListaMensagemRetorno }
     */
    public void setListaMensagemRetorno(ListaMensagemRetorno value) {
        this.listaMensagemRetorno = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://nfse.webpublico.com.br/iss/nfse_v1}CompNfse"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "compNfse"
    })
    public static class ListaNfse {

        @XmlElement(name = "CompNfse", required = true)
        protected TcCompNfse compNfse;

        /**
         * Gets the value of the compNfse property.
         *
         * @return possible object is
         * {@link TcCompNfse }
         */
        public TcCompNfse getCompNfse() {
            return compNfse;
        }

        /**
         * Sets the value of the compNfse property.
         *
         * @param value allowed object is
         *              {@link TcCompNfse }
         */
        public void setCompNfse(TcCompNfse value) {
            this.compNfse = value;
        }

    }

}
