//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 01:03:44 PM BRST 
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.TcIdentificacaoIntermediarioServico;
import br.com.webpublico.domain.dto.nfse10.TcIdentificacaoPrestador;
import br.com.webpublico.domain.dto.nfse10.TcIdentificacaoTomador;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prestador" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcIdentificacaoPrestador"/>
 *         &lt;element name="NumeroNfse" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsNumeroNfse" minOccurs="0"/>
 *         &lt;element name="PeriodoEmissao" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataInicial" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="DataFinal" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Tomador" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcIdentificacaoTomador" minOccurs="0"/>
 *         &lt;element name="IntermediarioServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcIdentificacaoIntermediarioServico" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "prestador",
        "numeroNfse",
        "periodoEmissao",
        "tomador",
        "intermediarioServico"
})
@XmlRootElement(name = "ConsultarNfseEnvio")
public class ConsultarNfseEnvio {

    @XmlElement(name = "Prestador", required = true)
    protected TcIdentificacaoPrestador prestador;
    @XmlElement(name = "NumeroNfse")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroNfse;
    @XmlElement(name = "PeriodoEmissao")
    protected br.com.webpublico.domain.dto.nfse10.ConsultarNfseEnvio.PeriodoEmissao periodoEmissao;
    @XmlElement(name = "Tomador")
    protected TcIdentificacaoTomador tomador;
    @XmlElement(name = "IntermediarioServico")
    protected TcIdentificacaoIntermediarioServico intermediarioServico;

    /**
     * Gets the value of the prestador property.
     *
     * @return possible object is
     * {@link TcIdentificacaoPrestador }
     */
    public TcIdentificacaoPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     *
     * @param value allowed object is
     *              {@link TcIdentificacaoPrestador }
     */
    public void setPrestador(TcIdentificacaoPrestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the numeroNfse property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNumeroNfse() {
        return numeroNfse;
    }

    /**
     * Sets the value of the numeroNfse property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNumeroNfse(BigInteger value) {
        this.numeroNfse = value;
    }

    /**
     * Gets the value of the periodoEmissao property.
     *
     * @return possible object is
     * {@link br.com.webpublico.domain.dto.nfse10.ConsultarNfseEnvio.PeriodoEmissao }
     */
    public br.com.webpublico.domain.dto.nfse10.ConsultarNfseEnvio.PeriodoEmissao getPeriodoEmissao() {
        return periodoEmissao;
    }

    /**
     * Sets the value of the periodoEmissao property.
     *
     * @param value allowed object is
     *              {@link br.com.webpublico.domain.dto.nfse10.ConsultarNfseEnvio.PeriodoEmissao }
     */
    public void setPeriodoEmissao(br.com.webpublico.domain.dto.nfse10.ConsultarNfseEnvio.PeriodoEmissao value) {
        this.periodoEmissao = value;
    }

    /**
     * Gets the value of the tomador property.
     *
     * @return possible object is
     * {@link TcIdentificacaoTomador }
     */
    public TcIdentificacaoTomador getTomador() {
        return tomador;
    }

    /**
     * Sets the value of the tomador property.
     *
     * @param value allowed object is
     *              {@link TcIdentificacaoTomador }
     */
    public void setTomador(TcIdentificacaoTomador value) {
        this.tomador = value;
    }

    /**
     * Gets the value of the intermediarioServico property.
     *
     * @return possible object is
     * {@link TcIdentificacaoIntermediarioServico }
     */
    public TcIdentificacaoIntermediarioServico getIntermediarioServico() {
        return intermediarioServico;
    }

    /**
     * Sets the value of the intermediarioServico property.
     *
     * @param value allowed object is
     *              {@link TcIdentificacaoIntermediarioServico }
     */
    public void setIntermediarioServico(TcIdentificacaoIntermediarioServico value) {
        this.intermediarioServico = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataInicial" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="DataFinal" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "dataInicial",
            "dataFinal"
    })
    public static class PeriodoEmissao {

        @XmlElement(name = "DataInicial", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataInicial;
        @XmlElement(name = "DataFinal", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataFinal;

        /**
         * Gets the value of the dataInicial property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDataInicial() {
            return dataInicial;
        }

        /**
         * Sets the value of the dataInicial property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setDataInicial(XMLGregorianCalendar value) {
            this.dataInicial = value;
        }

        /**
         * Gets the value of the dataFinal property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDataFinal() {
            return dataFinal;
        }

        /**
         * Sets the value of the dataFinal property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setDataFinal(XMLGregorianCalendar value) {
            this.dataFinal = value;
        }

    }

}
