//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 01:03:44 PM BRST 
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.TcValores;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDadosServico complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tcDadosServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Valores" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcValores"/>
 *         &lt;element name="ItemListaServico" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsItemListaServico"/>
 *         &lt;element name="CodigoCnae" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsCodigoCnae" minOccurs="0"/>
 *         &lt;element name="CodigoTributacaoMunicipio" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsCodigoTributacao" minOccurs="0"/>
 *         &lt;element name="Discriminacao" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsDiscriminacao"/>
 *         &lt;element name="CodigoMunicipio" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsCodigoMunicipioIbge"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDadosServico", propOrder = {
        "valores",
        "itemListaServico",
        "codigoCnae",
        "codigoTributacaoMunicipio",
        "discriminacao",
        "codigoMunicipio"
})
public class TcDadosServico {

    @XmlElement(name = "Valores", required = true)
    protected TcValores valores;
    @XmlElement(name = "ItemListaServico", required = true)
    protected String itemListaServico;
    @XmlElement(name = "CodigoCnae")
    protected Integer codigoCnae;
    @XmlElement(name = "CodigoTributacaoMunicipio")
    protected String codigoTributacaoMunicipio;
    @XmlElement(name = "Discriminacao", required = true)
    protected String discriminacao;
    @XmlElement(name = "CodigoMunicipio")
    protected int codigoMunicipio;

    /**
     * Gets the value of the valores property.
     *
     * @return possible object is
     * {@link TcValores }
     */
    public TcValores getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     *
     * @param value allowed object is
     *              {@link TcValores }
     */
    public void setValores(TcValores value) {
        this.valores = value;
    }

    /**
     * Gets the value of the itemListaServico property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getItemListaServico() {
        return itemListaServico;
    }

    /**
     * Sets the value of the itemListaServico property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setItemListaServico(String value) {
        this.itemListaServico = value;
    }

    /**
     * Gets the value of the codigoCnae property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getCodigoCnae() {
        return codigoCnae;
    }

    /**
     * Sets the value of the codigoCnae property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setCodigoCnae(Integer value) {
        this.codigoCnae = value;
    }

    /**
     * Gets the value of the codigoTributacaoMunicipio property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCodigoTributacaoMunicipio() {
        return codigoTributacaoMunicipio;
    }

    /**
     * Sets the value of the codigoTributacaoMunicipio property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCodigoTributacaoMunicipio(String value) {
        this.codigoTributacaoMunicipio = value;
    }

    /**
     * Gets the value of the discriminacao property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDiscriminacao() {
        return discriminacao;
    }

    /**
     * Sets the value of the discriminacao property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDiscriminacao(String value) {
        this.discriminacao = value;
    }

    /**
     * Gets the value of the codigoMunicipio property.
     */
    public int getCodigoMunicipio() {
        return codigoMunicipio;
    }

    /**
     * Sets the value of the codigoMunicipio property.
     */
    public void setCodigoMunicipio(int value) {
        this.codigoMunicipio = value;
    }

}
