//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 01:03:44 PM BRST 
//


package br.com.webpublico.domain.dto.nfse10;

import br.com.webpublico.domain.dto.nfse10.TcRps;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tcLoteRps complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tcLoteRps">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroLote" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsNumeroLote"/>
 *         &lt;element name="Cnpj" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsCnpj"/>
 *         &lt;element name="InscricaoMunicipal" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsInscricaoMunicipal"/>
 *         &lt;element name="QuantidadeRps" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsQuantidadeRps"/>
 *         &lt;element name="ListaRps">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Rps" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcRps" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsIdTag" />
 *       &lt;attribute name="versao" use="required" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tsVersao" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcLoteRps", propOrder = {
        "numeroLote",
        "cnpj",
        "inscricaoMunicipal",
        "quantidadeRps",
        "listaRps"
})
public class TcLoteRps {

    @XmlElement(name = "NumeroLote", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numeroLote;
    @XmlElement(name = "Cnpj", required = true)
    protected String cnpj;
    @XmlElement(name = "InscricaoMunicipal", required = true)
    protected String inscricaoMunicipal;
    @XmlElement(name = "QuantidadeRps")
    protected int quantidadeRps;
    @XmlElement(name = "ListaRps", required = true)
    protected br.com.webpublico.domain.dto.nfse10.TcLoteRps.ListaRps listaRps;
    @XmlAttribute(name = "Id")
    protected String id;
    @XmlAttribute(name = "versao", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String versao;

    /**
     * Gets the value of the numeroLote property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNumeroLote() {
        return numeroLote;
    }

    /**
     * Sets the value of the numeroLote property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNumeroLote(BigInteger value) {
        this.numeroLote = value;
    }

    /**
     * Gets the value of the cnpj property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCnpj() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCnpj(String value) {
        this.cnpj = value;
    }

    /**
     * Gets the value of the inscricaoMunicipal property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInscricaoMunicipal() {
        return inscricaoMunicipal;
    }

    /**
     * Sets the value of the inscricaoMunicipal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInscricaoMunicipal(String value) {
        this.inscricaoMunicipal = value;
    }

    /**
     * Gets the value of the quantidadeRps property.
     */
    public int getQuantidadeRps() {
        return quantidadeRps;
    }

    /**
     * Sets the value of the quantidadeRps property.
     */
    public void setQuantidadeRps(int value) {
        this.quantidadeRps = value;
    }

    /**
     * Gets the value of the listaRps property.
     *
     * @return possible object is
     * {@link br.com.webpublico.domain.dto.nfse10.TcLoteRps.ListaRps }
     */
    public br.com.webpublico.domain.dto.nfse10.TcLoteRps.ListaRps getListaRps() {
        return listaRps;
    }

    /**
     * Sets the value of the listaRps property.
     *
     * @param value allowed object is
     *              {@link br.com.webpublico.domain.dto.nfse10.TcLoteRps.ListaRps }
     */
    public void setListaRps(br.com.webpublico.domain.dto.nfse10.TcLoteRps.ListaRps value) {
        this.listaRps = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the versao property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersao(String value) {
        this.versao = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Rps" type="{http://nfse.webpublico.com.br/iss/nfse_v1}tcRps" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "rps"
    })
    public static class ListaRps {

        @XmlElement(name = "Rps", required = true)
        protected List<TcRps> rps;

        /**
         * Gets the value of the rps property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rps property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRps().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TcRps }
         */
        public List<TcRps> getRps() {
            if (rps == null) {
                rps = new ArrayList<TcRps>();
            }
            return this.rps;
        }

    }

}
